---
title: "01_id_subset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi", "dplyr")) {
  library(pkg, character.only = TRUE)
}

# read in the Burning Glass resume dat
get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }
# Get Some Data
con <- get_db_conn()
pers <- DBI::dbGetQuery(con, 'SELECT * FROM bgt_res.pers')

#cert <- DBI::dbGetQuery(con, 'SELECT * FROM bgt_res.cert')

DBI::dbDisconnect(con) 
```


```{r}
#function: take the dataset you want to be subsetted, and the area code, defalt to DC 47900
#output: subsetted dataset
#example: cert_subset <- subset(cert, "47900")

subset <- function(df = cert, code = "47900"){
  area <- grepl(code, pers$msa, fixed = TRUE)
  pers_area <- cbind(pers, area)
  pers_area <- pers_area%>%
    filter(area == T)
  id_area <- as.vector(pers_area$id)
  
  df_subset <- df %>% 
    filter(id %in% id_area)
  return(df_subset)
}





```

