---
title: "03_bg"
author: "Crystal"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    highlight: tango
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# load packages 
for (pkg in c("tidyverse",  "data.table", "R.utils",  "cowplot", "maditr", "stringr", "stringi", "mosaic", "dplyr", "ggplot2", "lubridate", "readxl")) {
  library(pkg, character.only = TRUE)
}
get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }
con <- get_db_conn()
cert <- DBI::dbGetQuery(con, "
                        SELECT * FROM bgt_res.cert
                        WHERE cert.id in (
                        SELECT ID FROM bgt_res.pers
                        WHERE pers.msa like '%47900%'
                        )"
)
ed <- DBI::dbGetQuery(con, "
                      SELECT id, degreetype FROM bgt_res.ed
                      WHERE ed.id in (
                      SELECT ID FROM bgt_res.pers
                      WHERE pers.msa like '%47900%'
                      )"
)

job <- DBI::dbGetQuery(con, "
                       SELECT * FROM bgt_res.job
                       WHERE job.id in (
                       SELECT ID FROM bgt_res.pers
                       WHERE pers.msa like '%47900%'
                       )"
)

pers <- DBI::dbGetQuery(con, "
                        SELECT * FROM bgt_res.pers
                        WHERE pers.msa like '%47900%'"
)

DBI::dbDisconnect(con)
#convert all dataframes to data table
cert <- as.data.table(cert)
ed <- as.data.table(ed)
job <- as.data.table(job)
pers <- as.data.table(pers)
```

#data preprocessing
#1.cleaning ed data table
```{r}
#data preprocessing
#1.cleaning ed data table
ed_rename <- ed%>%
  filter(!is.na(degreetype))%>%
  mutate(degree_certificate = if_else(str_detect(string = degreetype, 
                                                 pattern = "\\b(?i)(certificate|certificate)\\b"),T,F))%>%
  mutate(degree_somehs = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(10|11|9)\\b"), T,F))%>%
  mutate(degree_hs = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(12|High School|ged)\\b"), T,F))%>%
  mutate(degree_associate = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(Associate|associate)\\b"), T,F))%>%
  mutate(degree_bachelor = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(Bachelor|bachelor|Bachelors|BS|bs|B.S|BA|B.A|ba|AA|A.A|Undergraduate|undergraduate|postgraduate|Post-Graduate|post-graduate)\\b"), T,F))%>%
  mutate(degree_master = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(master|Master|MBA|M.S|MS|MD)\\b"), T,F))%>%
  mutate(degree_doctor = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(phd|Ph.D|postdoc|J.D|JD)\\b"), T,F))

# table(ed_rename$degree_associate)
# ed_rename%>%
#   group_by(degree_bachelor, degree_associate)%>%
#   summarize(N=n())

ed_rename_dup <- ed_rename%>%
  group_by(id)%>%
  mutate(number_degree = n())%>%
  filter(number_degree > 1)%>%
  as.data.table()%>%
  mutate(degree_highest = if_else(degree_doctor == T, "doctor", 
                                  if_else(degree_master == T, "master",
                                          if_else(degree_bachelor == T, "bachelor", 
                                                                                            if_else(degree_associate == T, "associate", 
                                                                                                    if_else(degree_hs == T, "highschool",
                                                                                                            if_else(degree_somehs == T, "somehs", 
                                                                                                                    if_else(degree_certificate ==T, "certificate", 
                                                                                                                    "others"))))))))

ed_rename_dup_unique <- ed_rename_dup%>%
  select(id, degree_highest)%>%
  tibble::rowid_to_column()%>%
  mutate(dup =T)%>%
pivot_wider(names_from = degree_highest, values_from = dup)%>%
  select(-rowid)


ed_rename_dup_unique <- replace(ed_rename_dup_unique, is.na(ed_rename_dup_unique), FALSE)


ed_rename_dup_sub <- ed_rename_dup_unique%>%
  group_by(id)%>%
  summarize(certificates = sum(certificate), somehss = sum(somehs), highschools= sum(highschool), associates = sum(associate), bachelors = sum(bachelor),masters= sum(master), doctors = sum(doctor))%>%
  group_by(id)%>%
  mutate(max = max(certificates, somehss, highschools, associates, bachelors, masters, doctors))

find_highest_degree <- function(vector){
  max = vector$max
  vector<- vector%>%
      mutate(degree_highest = if_else(vector[8] == max, "doctor", 
                                  if_else(vector[7] == max, "master",
                                          if_else(vector[6] == max, "bachelor", 
                                                                                            if_else(vector[5] == max, "associate", 
                                                                                                    if_else(vector[4] == max, "highschool",
                                                                                                            if_else(vector[3] == max, "somehs", 
                                                                                                                    if_else(vector[2] ==max, "certificate", 
                                                                                                                    "others"))))))))
  degree_highest <- vector$degree_highest
  return(degree_highest)
}


#this gives error
data <- apply(data, 1, function(x) find_highest_degree(x))



  # 
  # df <- group_by(id)%>%
  #     mutate(degree_highest = if_else(ed_rename_dup_sub[8] == max, "doctor", 
  #                                 if_else(ed_i_sum[7] == max, "master",
  #                                         if_else(ed_i_sum[6] == max, "bachelor", 
  #                                                                                           if_else(ed_i_sum[5] == max, "associate", 
  #                                                                                                   if_else(ed_i_sum[4] == max, "highschool",
  #                                                                                                           if_else(ed_i_sum[3] == max, "somehs", 
  #                                                                                                                   if_else(ed_i_sum[2] ==max, "certificate", 
  #                                                                                                                   "others"))))))))



# ed_final <- c()
# for(i in 1:length(ed_dup_id)){
#   message(paste("process #", ed_dup_id[i], i/length(ed_dup_id), "% done", sep = " "))
#   id_i <- ed_dup_id[i]
#   ed_i <- ed_rename_dup %>%
#     filter(id == id_i)
#   ed_i_sum <-  apply(ed_i[,3:9],2, sum)
#   max <- max(ed_i_sum)
#   ed_i_final <- ed_i%>%
#       mutate(degree_highest = if_else(ed_i_sum[7] == max, "doctor", 
#                                   if_else(ed_i_sum[6] == max, "master",
#                                           if_else(ed_i_sum[5] == max, "bachelor", 
#                                                                                             if_else(ed_i_sum[4] == max, "associate", 
#                                                                                                     if_else(ed_i_sum[3] == max, "highschool",
#                                                                                                             if_else(ed_i_sum[2] == max, "somehs", 
#                                                                                                                     if_else(ed_i_sum[1] ==max, "certificate", 
#                                                                                                                     "others"))))))))%>%
#     select(id, degree_highest)
#   ed_i_final <- ed_i_final[!duplicated(ed_i_final$id), ]
#   
#   ed_final <- rbind(ed_final, ed_i_final)
# }

#vector <- ed_rename_no_dup[100,]
# find_highest_degree <- function(df){
#   degree_highest <-c()
#   if(df$degree_doctor ==T){
#     degree_highest = "doctor"
#   } else if(df$degree_master ==T){
#       degree_highest = "master"
#   }else if(df$degree_bachelor ==T){
#       degree_highest = "bachelor"
#   }else if(df$degree_associate ==T){
#       degree_highest = "associate"
#   }else if(df$degree_hs ==T){
#       degree_highest = "highschool"
#   }else if(df$degree_somehs ==T){
#       degree_highest = "somehs"
#   }else if(df$degree_certificate==T){
#        degree_highest = "certificate"
#   }else{
#       degree_highest = "other"
#   }
#   return(degree_highest)
# }
#degree <- apply(ed_rename_no_dup, 1, function(x) find_highest_degree(x))

```

## no duplicates
```{r}
ed_rename_no_dup <- ed_clean%>%
  group_by(id)%>%
  mutate(number_degree = n())%>%
  filter(number_degree == 1)%>%
  filter(!degree_bachelor)%>%
  as.data.table()%>%
      mutate(degree_highest = if_else(degree_doctor == T, "doctor", 
                                  if_else(degree_master == T, "master",
                                          if_else(degree_bachelor == T, "bachelor", 
                                                                                            if_else(degree_associate == T, "associate", 
                                                                                                    if_else(degree_hs == T, "highschool",
                                                                                                            if_else(degree_somehs == T, "somehs", 
                                                                                                                    if_else(degree_certificate ==T, "certificate", 
                                                                                                                    "others"))))))))%>%
  select(id, degree_highest)




##########


```

#2.cleaning ed data table
```{r}
#2.cleaning ed data table
#create identifier for veterans
military <- "55-[0-9][0-9][0-9][0-9].[0-9][0-9]"
#extract unique military id
military_ids <- job %>% 
  filter(str_detect(job$onet, military))%>%
  distinct(id)%>%
  pull(id)
pers <- pers%>%
  mutate(veteran =if_else(id %in% military_ids, "veteran", "not veteran"))%>%
  select(id, gender, noofschooldegrees, noofcertifications, noofjobs, veteran)
```


```{r}
bg_full <- pers%>%
  left_join(ed, by="id")%>%
  left_join()

```


```{r}
vet_edu <- table(pers_military$veteran, pers_military$degree_highest)%>%
  as.data.frame()%>%
  rename("veteran" = "Var1", "education" = "Var2")%>%
  group_by(veteran)%>%
  summarize(education=education,percent = Freq / sum(Freq) * 100)%>%
  filter(!is.na(education))


unique(vet_edu$education)

vet_edu$education <- factor(vet_edu$education , levels = c("somehs", "hs", "bachelor and higher",  "others"))

ggplot(vet_edu, aes(x = education, y = percent, fill = veteran))+
  geom_bar(stat = "identity",position = 'dodge')+ 
  scale_fill_brewer(palette = "Set2")+
  #facet_wrap(~veteran) +
 # theme(axis.text.x = element_text(angle = 90))+ 
  labs(title = "Veteran's Education Distribution in Burning Glass Data")
```

