---
title: "03-Cleaned Burning Glass Data Profiling"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    highlight: tango
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# load packages 
for (pkg in c("tidyverse",  "data.table", "R.utils",  "cowplot", "maditr", "stringr", "stringi", "mosaic", "dplyr", "ggplot2", "lubridate", "readxl", "gt", "DataExplorer")) {
  library(pkg, character.only = TRUE)
}
get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }
con <- get_db_conn()
cert <- DBI::dbGetQuery(con, "
                        SELECT * FROM bgt_res.cert
                        WHERE cert.id in (
                        SELECT ID FROM bgt_res.pers
                        WHERE pers.msa like '%47900%'
                        )"
)
ed <- DBI::dbGetQuery(con, "
                      SELECT id, degreetype FROM bgt_res.ed
                      WHERE ed.id in (
                      SELECT ID FROM bgt_res.pers
                      WHERE pers.msa like '%47900%'
                      )"
)

job <- DBI::dbGetQuery(con, "
                       SELECT id, onet, jobposition, sector, startdate, enddate FROM bgt_res.job
                       WHERE job.id in (
                       SELECT ID FROM bgt_res.pers
                       WHERE pers.msa like '%47900%'
                       )"
)

pers <- DBI::dbGetQuery(con, "
                        SELECT * FROM bgt_res.pers
                        WHERE pers.msa like '%47900%'"
)

# skill <- DBI::dbGetQuery(con, "
#                          SELECT * FROM bgt_res.skill
#                          WHERE skill.id in (
#                          SELECT ID FROM bgt_res.pers
#                          WHERE pers.msa like '%47900%'
#                          )"
# )

tbl <- RPostgreSQL::dbGetQuery(con, "SELECT * FROM bgt.progression")

DBI::dbDisconnect(con)

#convert all dataframes to data table
cert <- as.data.table(cert)
ed <- as.data.table(ed)
job <- as.data.table(job)
pers <- as.data.table(pers)
```

# Data Preprocessing
## Clean each data table before joining
### 1. cleaning ed data table
```{r}
ed_rename <- ed%>%
  filter(!is.na(degreetype))%>%
  mutate(degree_certificate = if_else(str_detect(string = degreetype, 
                                                 pattern = "\\b(?i)(certificate|certificate)\\b"),T,F))%>%
  mutate(degree_somehs = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(10|11|9)\\b"), T,F))%>%
  mutate(degree_hs = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(12|High School|ged)\\b"), T,F))%>%
  mutate(degree_associate = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(Associate|associate)\\b"), T,F))%>%
  mutate(degree_bachelor = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(Bachelor|bachelor|Bachelors|BS|bs|B.S|BA|B.A|ba|AA|A.A|Undergraduate|undergraduate|postgraduate|Post-Graduate|post-graduate)\\b"), T,F))%>%
  mutate(degree_master = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(master|Master|MBA|M.S|MS|MD)\\b"), T,F))%>%
  mutate(degree_doctor = if_else(str_detect(string = degreetype, 
                              pattern = "\\b(?i)(phd|Ph.D|postdoc|J.D|JD)\\b"), T,F))

#duplicated degree
ed_rename_dup <- ed_rename%>%
  group_by(id)%>%
  mutate(number_degree = n())%>%
  filter(number_degree > 1)%>%
  as.data.table()%>%
  mutate(degree_highest = if_else(degree_doctor == T, "doctor", 
                                  if_else(degree_master == T, "master",
                                          if_else(degree_bachelor == T, "bachelor", 
                                                                                            if_else(degree_associate == T, "associate", 
                                                                                                    if_else(degree_hs == T, "highschool",
                                                                                                            if_else(degree_somehs == T, "somehs", 
                                                                                                                    if_else(degree_certificate ==T, "certificate", 
                                                                                                                    "others"))))))))

ed_rename_dup <- ed_rename_dup%>%
  select(id, degree_highest)%>%
  tibble::rowid_to_column()%>%
  mutate(dup =T)%>%
pivot_wider(names_from = degree_highest, values_from = dup)%>%
  select(-rowid)

ed_rename_dup <- replace(ed_rename_dup, is.na(ed_rename_dup), FALSE)

ed_rename_dup <- ed_rename_dup %>%
  arrange(id, -doctor, -master, -bachelor, -associate, -highschool, -somehs, -certificate, -others) %>%
  group_by(id)%>%
  filter(row_number()==1)%>%
  mutate(degree_highest = c("certificate", "somehs", "highschool", "associate", "bachelor","master", "doctor")[which.max(x = c(certificate, somehs, highschool, associate, bachelor, master, doctor))]) %>%
  select(id, degree_highest)%>%
  as.data.table()

## users with no duplicated degree
ed_rename_no_dup <- ed_rename%>%
  group_by(id)%>%
  mutate(number_degree = n())%>%
  filter(number_degree == 1)%>%
  filter(!degree_bachelor)%>%
  as.data.table()%>%
      mutate(degree_highest = if_else(degree_doctor == T, "doctor", 
                                  if_else(degree_master == T, "master",
                                          if_else(degree_bachelor == T, "bachelor", 
                                                                                            if_else(degree_associate == T, "associate", 
                                                                                                    if_else(degree_hs == T, "highschool",
                                                                                                            if_else(degree_somehs == T, "somehs", 
                                                                                                                    if_else(degree_certificate ==T, "certificate", 
                                                                                                                    "others"))))))))%>%
  select(id, degree_highest)

##join the two table: ed_rename_no_dup, ed_rename_dup
list = list(ed_rename_no_dup, ed_rename_dup)
ed_cleaned <- rbindlist(list)

```

### 2. cleaning ed data table
```{r message=FALSE, warning=FALSE}
#create identifier for veterans
military <- "55-[0-9][0-9][0-9][0-9].[0-9][0-9]"
#extract unique military id
military_ids <- job %>% 
  filter(str_detect(job$onet, military))%>%
  distinct(id)%>%
  pull(id)
pers_cleaned <- pers%>%
  mutate(veteran =if_else(id %in% military_ids, "veteran", "not veteran"))%>%
  select(id, gender, noofschooldegrees, noofcertifications, noofjobs, veteran)
```

### 3. clean cert data table
```{r message=FALSE, warning=FALSE}
cert_cleaned <- cert%>%
  rename("cert_name" = "name", "cert_type"="type", "cert_position" = "position")
```

### 4. clean job data table
```{r message=FALSE, warning=FALSE}
# extracted from Joanna's code in 02_data_profiling_DC.Rmd
job_cleaned <- job %>%
  filter(!is.na(onet) & !is.na(jobposition) &  !is.na(startdate) & !is.na(enddate)) %>%
  mutate(start_year = year(startdate), end_year = year(enddate), start_month = month(startdate), end_month = month(enddate), start_day = day(startdate), end_day = day(enddate)) 
```

## Join All Cleaned Data Tables
```{r}
bg_full <- pers_cleaned%>%
  left_join(ed_cleaned, by="id")%>%  #one person would only have one highest degree
  left_join(cert_cleaned, by="id")%>%  #one person might have multiple certificates
  left_join(job_cleaned, by = "id") #one person might have multiple job listed
```

# Data Profiling on Joined Burning Galss Data
```{r}
data_profiling <- function(df){
  nrow = nrow(df)
summary_table <- tibble(var = names(df),
       variable_type = map_chr(.x = df, .f = function(col) class(x = col)),                 
       num_unique = map_int(.x = df, .f = function(col) length(x = unique(x = col))),
       num_missing = map_int(.x = df, .f = function(col) sum(x = is.na(x = col)))) %>%
  mutate(perc_missing = round(x = 100 * num_missing / nrow, digits = 2L))

return(summary_table)
}

# data profiling 1. demographic, education
bg_demographic <- bg_full%>%
  select(id, gender, veteran, degree_highest)
bg_demographic <- bg_demographic[!duplicated(bg_demographic$id), ]

bg_demographic%>%
  data_profiling()%>%
  gt()%>%
  tab_header(
    title =" data profiling on demographic and education variables"
  )

## data profiling 2. job
bg_job <- bg_full %>%
  select(id, onet, jobposition, sector, startdate, enddate, start_month, end_month, start_day, end_day)%>%
  filter(!is.na(onet))

bg_job%>%
  group_by(id)%>%
  summarize()
bg_demographic <- bg_demographic[!duplicated(bg_demographic$id), ]

```

# Demographic
## Veteran v.s. Non-veteran's Gender
```{r fig.width=6, fig.height=4, message=FALSE, warning=FALSE, paged.print=FALSE}
vet_sex <- table(bg_full$veteran, bg_full$gender)%>%
  as.data.frame()%>%
  rename("veteran" = "Var1", "gender" = "Var2")%>%
  group_by(veteran)%>%
  summarize(gender=gender,percent = Freq / sum(Freq) * 100)

ggplot(vet_sex, aes(x = gender, y = percent, fill=veteran))+
  geom_bar( stat = "identity", position = "dodge")+ 
  scale_fill_brewer(palette = "Set2")
```


# Career
## Veteran v.s. Non-veteran's Degree Level
```{r fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
bg_vet_edu<- bg_full%>%
  select(id, veteran, degree_highest)
bg_vet_edu <- bg_vet_edu[!duplicated(bg_vet_edu$id), ]

vet_edu <- table(bg_vet_edu$veteran, bg_vet_edu$degree_highest)%>%
  as.data.frame()%>%
  rename("veteran" = "Var1", "education" = "Var2")%>%
  group_by(veteran)%>%
  summarize(education=education,percent = Freq / sum(Freq) * 100)%>%
  filter(!is.na(education))

unique(vet_edu$education)

vet_edu$education <- factor(vet_edu$education , levels = c("others","certificate","somehs", "highschool", "associate", "bachelor",  "master","doctor"))

ggplot(vet_edu, aes(x = education, y = percent, fill = veteran))+
  geom_bar(stat = "identity",position = 'dodge')+ 
  scale_fill_brewer(palette = "Set2")+
  #facet_wrap(~veteran) +
 # theme(axis.text.x = element_text(angle = 90))+ 
  labs(title = "Veteran's Education Distribution in Burning Glass Data")
```

## Veteran v.s. Non-veteran's Certificates
```{r fig.width=11, fig.height=5, message=FALSE, warning=FALSE, paged.print=FALSE}
cert_vet <- bg_full%>%
  filter(!is.na(cert_name))%>%
  group_by(veteran, cert_name)%>%
  summarize(ttl_cert = n())%>%
  group_by(veteran)%>%
  top_n(10, ttl_cert)%>%
  group_by(veteran)%>%
  summarize(cert_name=cert_name, percent = ttl_cert / sum(ttl_cert) * 100)

ggplot(cert_vet, aes(x = cert_name, y = percent, fill = veteran))+
  geom_bar(stat = "identity",position = 'dodge')+ 
  scale_fill_brewer(palette = "Set2")+
  coord_flip()+
  labs(title = "Top Certificates for Veterans v.s. Non-Veterans", x = "certificate")
```


```{r fig.width=12, fig.height=10}
plot_bar(bg_full)

```


```{r fig.width=15, fig.height=12}
plot_histogram(bg_full)
```

