---
title: "06_promotion_demotion_nochange"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
for (pkg in c("tidyverse",  "data.table", "R.utils", "maditr", "stringr", "stringi", "dplyr", "ggplot2", "lubridate", "gt", "DataExplorer")) {
  library(pkg, character.only = TRUE)
}

#double check your working directory
source("~/git/dspg20career/src/burningglass/03_clean_bgt.R", echo = T, prompt.echo = "", spaced = F)
bg_clean_ls <- clean_bg(job = job, ed = ed, pers = pers, onet = onet)

bg_all_demographic <- bg_clean_ls$bg_all_demographic
bg_vet_demographic <- bg_clean_ls$bg_vet_demographic
bg_all_job <- bg_clean_ls$bg_all_job
bg_vet_job <- bg_clean_ls$bg_vet_job


uva_color_palette <- 
c("#232D4B", #space cadet
  "#2C4F6B", #indigo dye
  "#0E879C", #blue munsell
  "#60999A", #cadet blue
  "#D1E0BF", #tea green
  "#D9E12B", #pear
  "#E6CE3A", #citrine
  "#E6A01D", #marigold
  "#E57200" #princeton orange
)
```

```{r}
vet_id <- bg_all_demographic%>%
  select(id, veteran)
```


```{r}
table(bg_all_job$start_year)
class(bg_all_job$jobposition)

first_job <- bg_all_job%>%
  group_by(id)%>%
  mutate(max_jobposition = max(jobposition, na.rm=T), match = if_else(jobposition == max_jobposition, T, F))%>%
  filter(max_jobposition >0)%>%
  filter(match == T)%>%
  select(id, start_year)%>%
  rename(first_job_start_year = start_year)

last_job <- bg_all_job%>%
  group_by(id)%>%
  mutate(min_jobposition = min(jobposition, na.rm=T), match = if_else(jobposition == min_jobposition, T, F))%>%
  filter(min_jobposition >0)%>%
  filter(match == T) %>%
  mutate(more_than_one_year_out = if_else(end_year <= 2017, T, F)) 

last_job <- last_job%>%
  select(id, end_year, more_than_one_year_out, noofjobs, onet_job_zone)%>%
  rename(last_job_end_year = end_year)

first_last_job <- left_join(first_job, last_job, by = "id")

first_last_job <- left_join(first_last_job, vet_id, by = "id")

first_last_job <- first_last_job%>%
  mutate(first_job_start_cat = if_else(first_job_start_year < 2000, "before 2000", if_else(first_job_start_year < 2010, "2000-2010", "2010 and later")))%>%
  mutate(time_in_job_market = 2018- first_job_start_year)

table(first_last_job$first_job_start_cat)
#table(duplicated(first_last_job$id)) #check duplicates
table(first_last_job$more_than_one_year_out)
```


#number of jobs
```{r}
first_last_job$first_job_start_cat <- factor(first_last_job$first_job_start_cat, levels = c("2010 and later","2000-2010", "before 2000"))

ggplot(first_last_job, aes(x=veteran, y=noofjobs, fill = first_job_start_cat)) + 
  geom_boxplot(outlier.size = 0.1)+
  coord_flip()+
  scale_fill_manual(values=c(uva_color_palette[2], uva_color_palette[4], uva_color_palette[5]),  guide = guide_legend(reverse = T))+
  labs(fill="time entering \n job market", y = "number of jobs")+   
  theme_classic()

ggplot(first_last_job, aes(x=first_job_start_cat, y=noofjobs, fill = veteran)) + 
  geom_boxplot(outlier.size = 0.1)+
  coord_flip()+
  scale_fill_manual(values=c(uva_color_palette[2], uva_color_palette[8]),  guide = guide_legend(reverse = T))+
   labs(fill="veteran", y = "number of jobs", x="time entering job market")+   
  theme_classic()

```

# Veteran, job zone change
not using date
```{r}
bg_vet_job_change_short <- bg_vet_job%>%
  group_by(id)%>%
  mutate(ttl = n(), job_position = seq.int(ttl))%>%
 select(id, job_position, onet_job_zone)%>%
  spread("job_position", "onet_job_zone")

vet_more_than_one_job <- bg_vet_job_change_short%>%
  filter(!is.na(`2`))
```


using date
```{r}
bg_vet_job_change<- bg_vet_job%>%
 select(id, startdate, enddate, job_duration_day, onet_job_zone, onet_title)


```

