---
title: "10_exploring_sequences"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
for (pkg in c("tidyverse",  "data.table", "R.utils", "maditr", "stringr", "stringi", "dplyr", "ggplot2", "lubridate", "gt", "DataExplorer", "TraMineR", "TraMineRextras", "cluster", "viridis")) {
  library(pkg, character.only = TRUE)
}

uva_color_palette <- 
c("#232D4B", #space cadet
  "#2C4F6B", #indigo dye
  "#0E879C", #blue munsell
  "#60999A", #cadet blue
  "#D1E0BF", #tea green
  "#D9E12B", #pear
  "#E6CE3A", #citrine
  "#E6A01D", #marigold
  "#E57200" #princeton orange
)
```

```{r}
bg_vet_job <- read_csv("~/git/DSPG2020/career/data/04_bg_vet_job.csv")
bg_vet_demographic <- read_csv("~/git/DSPG2020/career/data/02_bg_vet_demographic.csv")

# We are choosing years as our unit of analysis because months are unreliable. We are also taking the highest O*NET job zone for a given year to deal with overlapping jobs.
bg_vet_job_seq <- bg_vet_job %>%
  mutate(startyear = year(startdate), endyear = year(enddate)) %>%
  select("id", "startyear", "endyear", "onet_job_zone")%>%
  group_by(id)%>%
  arrange(desc(onet_job_zone))%>%
  group_by(id)%>%
  distinct(id, startyear, endyear, .keep_all = TRUE)

# We need an auxillary table with the year of entering the job market to align the sequences
bg_vet_job_first <- bg_vet_job_seq %>% 
  select("id", "startyear") %>% group_by(id) %>% transmute(enter = min(startyear)) %>% distinct() %>% ungroup()

# The seqformat() function does not like any data that has been previously grouped. Here we are "resetting" the data so that it will pass through the function.
bg_vet_job_seq <- as.matrix(bg_vet_job_seq)
bg_vet_job_seq <- as.data.frame(bg_vet_job_seq)
bg_vet_job_first <- as.matrix(bg_vet_job_first)
bg_vet_job_first <- as.data.frame(bg_vet_job_first)

# The input for the function is the prepared sequence table. The data is in format SPELL and we are transforming to format STS. By setting process = TRUE we can align the sequences using the prepared auxillary table.
sts_vet <- seqformat(bg_vet_job_seq, from = "SPELL", to = "STS",
                     id = "id",  begin = "startyear", end = "endyear", 
                     status = "onet_job_zone", process = TRUE,
                     pdata = bg_vet_job_first, pvar = c("id", "enter"))
# Here we are renaming columns to be in format "yn" (year in the job market)
names(sts_vet) <- paste0(1:100)

# Writing the final table as a csv
#write.csv(sts_vet, "sts_vet_55.csv")

sts_vet <- seqdef(sts_vet, cpal = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2],uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), left="DEL", gaps="unemployed", right="DEL",
labels = c("Missing job zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployment"))

```

```{r}
# Seqmtplot displays the mean time spent in each state
seqmtplot(sts_vet, main = "Mean time distribution plot", ylim = c(0, 10), border = NA, with.legend= FALSE)

# Seqdplot represents the sequence of the cross-sectional state frequencies by position
seqdplot(sts_vet, main = "Sequence distribution plot", border = NA, with.legend = "right")

# Seqfplot displays the most frequent sequences
seqfplot(sts_vet, main = "Sequence frequency plot", with.legend = TRUE ,pbarw = TRUE)

seqHtplot(sts_vet, main = "Entropy index plot", with.legend = TRUE)


#This indicator is called the entropy index Billari [2001] It equals 0 when all cases are in the same state (it is thus easyto predict in which state an individual is) It is maximum when the cases are equally distributed betweenthe states of the alphabet (it is thus hard to predict in whichstate an individual is)

# Transition matrix
tr <- seqtrate(sts_vet)
round(tr, 2)

transition.matrix.df <- as.data.frame(tr)
transition.matrix.df$startState <- row.names(transition.matrix.df)
transition.matrix.df <- melt(transition.matrix.df)
colnames(transition.matrix.df)[colnames(transition.matrix.df) == "variable"] <- "endState"
                                        
ggplot(data = transition.matrix.df, aes(x = endState, y = factor(startState,        levels = rev(levels(factor(startState)))), fill = value)) + 
  geom_tile() +    
  geom_text(aes(label=round(value,3))) +  
  scale_x_discrete(position = "top") +  
  scale_fill_gradient(low = "white", high = "#E57200") +
  theme(legend.position="bottom", panel.background = element_blank(),         plot.title = element_text(face = "bold")) +  
  labs(fill = "Transition Probability",        
       title = "Transition Matrix for Veterans",     
       y = "Current Job",       
       x = "Next Job")

sts_vet_demographic <- left_join(sts_vet %>% mutate(id = as.numeric(rownames(sts_vet))), bg_vet_demographic, by = "id")

sts_vet_demographic <- seqdef(sts_vet_demographic, 1:100, left="DEL", gaps="unemployed", right="DEL")

```

```{r fig.height=10}
dist.mostfreq <- seqdist(sts_vet, method = "LCS", refseq = 0)

demo <- bg_vet_demographic %>% filter(id %in% as.numeric(rownames(sts_vet)))

seqIplot(sts_vet, border = NA, group = demo$gender, sortv = dist.mostfreq,
         xlim = c(0,60))

seqIplot(sts_vet, border = NA, group = demo$degree_highest, sortv = dist.mostfreq,
         xlim = c(0,60))

```
```{r}
# Crystal's Code for TSE
#bg_vet_job <-read_csv("~/git/DSPG2020/career/data/04_bg_vet_job.csv")%>%
 # mutate(is_onet55 = if_else(str_detect(onet, "55-[0-9][0-9][0-9][0-9].[0-9][0-9]"), T, F))%>%
 # select(id,onet,is_onet55, onet_job_zone, startdate, enddate, start_year, end_year, onet_title, date_enter_job_market, job_duration_day)%>%
 # mutate(year_enter_job_market = year(date_enter_job_market))

#vet_endmilitary <- bg_vet_job%>%
#  mutate(date_end_onet55 = if_else(is_onet55==T, enddate, as.Date(NA)))%>%
#  filter(!is.na(date_end_onet55))%>%  #exluce people who don't have valid onet55 code
#  select(id, date_end_onet55) %>%
  #keep the latest onet55 job
#  group_by(id)%>%   
#  arrange(desc(date_end_onet55))%>%
#  group_by(id)%>%
#  distinct(id, .keep_all = TRUE)

#bg_vet_job  <- inner_join(bg_vet_job, vet_endmilitary, by = "id")

#bg_vet_job_seq <- bg_vet_job %>%
#  select(id, end_year, onet_job_zone, startdate, enddate, job_duration_day, date_end_onet55, year_enter_job_market)%>%
#  filter(startdate > date_end_onet55)  %>% #find jobs that came after the date ended onet55 job
#  mutate(start_year = year(startdate))


#bg_vet_job_seq <- bg_vet_job_seq %>%
#  mutate(start_year = start_year - year_enter_job_market + 1)%>%
#  mutate(end_year = end_year - year_enter_job_market + 1)%>%
#  select(id, start_year, end_year, onet_job_zone)%>%
#  group_by(id)%>%
#  arrange(desc(onet_job_zone))%>%
#  group_by(id)%>%
#  distinct(id, start_year, end_year, .keep_all = TRUE)


#bg_vet_job_seq <- as.matrix(bg_vet_job_seq)
#bg_vet_job_seq <- as.data.frame(bg_vet_job_seq)
#class(bg_vet_job_seq)

#sts_vet <- seqformat(bg_vet_job_seq, from = "SPELL", to = "STS",
#                     id = "id",  begin = "start_year", end = "end_year", 
#                     status = "onet_job_zone", process = FALSE)
#vet.seq <- seqdef(sts_vet, left="DEL", gaps="unemployment", right="DEL",
#                  labels = c("1", "2", "3", "4", "5", "unknown"))
#transition <- seqetm(vet.seq, method = "transition")
#transition
#dim(transition)
#transition[1, 1:7] <- c("Begin", "Promotion", "Promotion", "Promotion", "Promotion", "Demotion", "NA")
#transition[2, 1:7] <- c("Demotion", "Begin", "Promotion", "Promotion", "Promotion", "Demotion", "NA")
#transition[3, 1:7] <- c("Demotion", "Demotion", "Begin", "Promotion", "Promotion", "Demotion", "NA")
#transition[4, 1:7] <- c("Demotion", "Demotion", "Demotion", "Begin", "Promotion", "Promotion", "NA")
#transition[5, 1:7] <- c("Demotion", "Demotion", "Demotion", "Demotion", "Begin", "Promotion", "NA")
#transition[6, 1:7] <- c("Promotion", "Promotion", "Promotion", "Promotion", "Promotion", "Begin", "NA")
#transition[7, 1:7] <- c("NA", "NA", "NA", "NA", "NA", "NA", "NA")



#transition


#vet.tse <- seqformat(sts_vet[1:100, ], from = "STS", to = "TSE", tevent = transition)

#vet.seq.tse <- seqecreate(id = vet.tse$id, timestamp = vet.tse$time, event = vet.tse$event)
#class(vet.seq.tse)
#vet.seq.tse[1]
```


```{r}
#sts_vet_sub <- seqefsub(sts_vet, pMinSupport = 0.05)
#sts_vet_sub[1:5]

#plot(sub_vet_sub[1:15], col = "cyan", ylab = "Frequency", xlab = "Subsequences", cex = 1.5)

# group = mvad$gcse5eq
# Discriminant sequences 
#Aim is to identify the frequent sequences that are moststrongly related with a given factor.Discriminant power is evaluated withp-value of a Chi-squareindependence test.Functionseqecmpgroup()To which we provide the frequent subsequence object and agroup factor (gcse5eq).A Bonferroni correction is applied when passing argumentmethod="bonferroni".
#sts_vet_desc <- seqecmpgroup(sub_vet_sub, group = demo$degress_highest, method = "bonferroni")
#sts_vet_desc[1:5]
#plot(sts_vet_desc[1:15], cex = 1.5)
#plot(sts_vet_desc[1:15], ptype = "resid", cex = 1.5)

# Extract sequential association rules 
# Sequential association ruleA rule subseq1→subseq2such that1Has a minimal support2When subseq1occurs, it is most often followed by subseq2Extracted from frequent sequences.
#rules <- TraMineR:::seqerules(sub_vet_sub)
#rules[order(rules$Lift, decreasing = TRUE)[1:10], 1:4]

```


```{r}
statd <- seqstatd(sts_vet)
states <- statd$Frequencies
states <- as.data.frame(states)
names(states) <- paste0(1:100)
states <- states %>% rownames_to_column(var = "state")
states <- melt(states, id = "state")

v_states <- statd$ValidStates
v_states <- as.data.frame(v_states)
v_states <- v_states %>% rownames_to_column(var = "variable")

ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/8068),
            size = 2) +
  scale_y_continuous(name = "Share of careers in a job state",
                     sec.axis = sec_axis(trans = ~.*(8068), name = "Number of careers in year of career")) +
  xlim(0,78) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Visualizing career paths of veterans: Job states over time",
       fill = "Job state") +
  theme_classic() +
  theme(legend.position = "bottom")

meant <- seqmeant(sts_vet)
meant <- as.data.frame(meant)
meant <- meant %>% rownames_to_column(var = "state")

ggplot(data = meant, aes(x = state, y = Mean, fill = state)) +
  geom_col() +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  scale_x_discrete(name = "Job state", labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  labs(title = "Mean time spent in each state",
       fill = "Job state") +
  ylab("Mean time (years)") +
  theme_classic() +
  theme(legend.position = "none")

lengths <- seqlength(sts_vet)
lengths <- as.data.frame(lengths)
lengths <- lengths %>% rownames_to_column(var = "id")
length_sum <- quantile(lengths$Length)
length_sum <- as.data.frame(length_sum)
length_sum <- length_sum %>% rownames_to_column(var = "measure")
summary(lengths)

ggplot(data = lengths, aes(x = Length)) +
  geom_histogram(binwidth = 5, colour="black", fill = "white") +
  geom_vline(data = length_sum, aes(xintercept = 20,
               color="Median"), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 13,
               color= "1st Qu."), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 29,
               color="3rd Qu."), linetype="solid", size=1) +
    geom_vline(data = length_sum, aes(xintercept = 1,
               color="Min"), linetype="solid", size=1) +
    geom_vline(data = length_sum, aes(xintercept = 86,
               color="Max"), linetype="solid", size=1) +
  xlim(1,86) +
  labs(title = "Sequence lengths for all veterans in DC metro area",
       caption = "Data: BGT Resumes") +
  xlab("Sequence length (years)") +
  ylab("Count of sequences") +
#  annotate("text", x=74, y=364, 
#           label=paste("Min. =", length_sum[1,2],"\n Max. = ", length_sum[5,2]), size=3) +
  theme_classic() +
  theme(legend.position=c(.8,.5)) +
  scale_color_viridis_d(name = "Values", limits = c("Min", "1st Qu.", "Median", "3rd Qu.", "Max"))

 # scale_color_manual(name = "Values", values = c("1st Qu." = "#33638DFF", "Median" #= "#440154FF", "3rd Qu." = "#29AF7FFF"), limits = c("1st Qu.", "Median", "3rd Qu."))
  
```

```{r}
## Crystal
#import veteran job data
#bg_vet_job <-read_csv("~/git/DSPG2020/career/data/04_bg_vet_job.csv")%>%
#  mutate(year_enter_job_market = year(date_enter_job_market))%>%
#  select(-noofjobs, -sector, -tenure)
#colnames(bg_vet_job)

#veterans and the date they ended their last ONET 55 job
#vet_endmilitary <- bg_vet_job%>%
#  mutate(date_end_onet55 = if_else(is_onet55==T, enddate, as.Date(NA)))%>%
#  filter(!is.na(date_end_onet55))%>%  #exluce people who don't have valid onet55 code
#  select(id, date_end_onet55) %>%
  #keep the latest onet55 job
#  group_by(id)%>%   
#  arrange(desc(date_end_onet55))%>%
#  group_by(id)%>%
#  distinct(id, .keep_all = TRUE) 

#bg_vet_job  <- inner_join(bg_vet_job, vet_endmilitary, by = "id")

## sequence data
#bg_vet_job_seq <- bg_vet_job %>%
#  select(id, end_year, onet_job_zone, startdate, enddate, job_duration_day, date_end_onet55, year_enter_job_market)%>%
#  mutate(year_end_onet55 = year(date_end_onet55))%>%
#  select(-year_enter_job_market)%>%
#  filter(startdate >= date_end_onet55)%>% #find jobs that came after the date ended onet55 job
#  filter(onet_job_zone != 55)  %>%  #filter out 55 jobs that have the same start and end date  
#  mutate(start_year = year(startdate))


#check <- bg_vet_job_seq%>%
#  mutate(year_until_first_job = start_year- year_end_onet55)%>%
#  group_by(id)%>%
#  summarize(years = min(year_until_first_job))

#ggplot(check, aes(x = years)) + 
#  geom_histogram(binwidth = 1.4) + 
#  labs(title = "", x = "years until first job") 

#summary(check$years)

#bg_vet_job_seq <- bg_vet_job_seq%>%
#  mutate(start_year = start_year - year_end_onet55 + 1)%>%  #transform from calender year to year start sequence analysis
#  mutate(end_year = end_year - year_end_onet55 + 1) %>% #transform from calender year to year start sequence analysis
#  select(id, start_year, end_year, onet_job_zone)%>%
#  group_by(id)%>%
#  arrange(desc(onet_job_zone))%>%
#  group_by(id)%>%
#  distinct(id, start_year, end_year, .keep_all = TRUE)

#bg_vet_job_seq <- as.matrix(bg_vet_job_seq)
#bg_vet_job_seq <- as.data.frame(bg_vet_job_seq)

#sts_vet <- seqformat(bg_vet_job_seq, from = "SPELL", to = "STS",
#                     id = "id",  begin = "start_year", end = "end_year", 
#                     status = "onet_job_zone", process = FALSE)

#obtain jobs that appear after 10 years they exit military 
#sts_vet_qu <- sts_vet[, 1:10]

# Here we are renaming columns to be in format "yn" (year in the job market)
#names(sts_vet) <- paste0("y", 1:ncol(sts_vet))

sts_vet_qu <- sts_vet
```

```{r}
statd <- seqstatd(vet.seq)
states <- statd$Frequencies
states <- as.data.frame(states)
names(states) <- paste0(1:10)
states <- states %>% rownames_to_column(var = "state")
states <- melt(states, id = "state")

v_states <- statd$ValidStates
v_states <- as.data.frame(v_states)
v_states <- v_states %>% rownames_to_column(var = "variable")

seqdplot(vet.seq)
seqmtplot(vet.seq)

ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
 # geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/5185),
 #           size = 2) +
  scale_y_continuous(name = "Share of careers in a job state") +
  xlim(0,10) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "gray", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Transitional unemployed", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Visualizing career paths of veterans: Job states over time",
       fill = "Job state") +
  theme_classic() +
  theme(legend.position = "bottom")

meant <- seqmeant(vet.seq)
meant <- as.data.frame(meant)
meant <- meant %>% rownames_to_column(var = "state")

ggplot(data = meant, aes(x = state, y = Mean, fill = state)) +
  geom_col() +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2],uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "#CBBEB5", "#CBBEB5","#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Transition unemployed", "Unemployed", "Unemployed/Exit")) +
  scale_x_discrete(name = "Job state", labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Transition unemployed", "Unemployed", "Unemployed/Exit")) +
  labs(title = "Mean time spent in each state",
       fill = "Job state") +
  ylab("Mean time (years)") +
  theme_classic() +
  theme(legend.position = "none")
```

```{r}

library(scales)
ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/8068),
            size = 2) +
  scale_y_continuous(name = "Share of careers in a job state",
                     sec.axis = sec_axis(trans = ~.*(8068), name = "Number of careers in year of career")) +
  xlim(0,78) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Visualizing career paths of veterans: Job states over time",
       fill = "Job state") +
  theme_classic() +
  theme(legend.position = "bottom")

ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/5185),
            size = 2) +
  scale_y_continuous(name = "Share of careers in a job state",
                     sec.axis = sec_axis(trans = ~.*(5185), name = "Number of careers in year of career")) +
  xlim(0,10) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "gray", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Transitional unemployed", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Visualizing career paths of veterans: Job states over time",
       fill = "Job state") +
  theme_classic() +
  theme(legend.position = "bottom")

ggplot(data = lengths, aes(x = Length)) +
  geom_histogram(binwidth = 5, colour="black", fill = "white") +
  geom_vline(data = length_sum, aes(xintercept = 20,
                                    color="Median"), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 13,
                                    color= "1st Qu."), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 29,
                                    color="3rd Qu."), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 1,
                                    color="Min"), linetype="solid", size=1) +
  geom_vline(data = length_sum, aes(xintercept = 86,
                                    color="Max"), linetype="solid", size=1) +
  xlim(1,86) +
  labs(title = "Lengths of career sequences for veteran's whole careers",
       caption = "Data: BGT Resumes") +
  xlab("Sequence length (years)") +
  ylab("Count of sequences") +
  #  annotate("text", x=74, y=364, 
  #           label=paste("Min. =", length_sum[1,2],"\n Max. = ", length_sum[5,2]), size=3) +
  theme_classic() +
  theme(legend.position=c(.8,.5)) +
  scale_color_viridis_d(name = "Values", limits = c("Min", "1st Qu.", "Median", "3rd Qu.", "Max"))

ggplot(data = meant, aes(x = state, y = Mean, fill = state)) +
  geom_col() +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  scale_x_discrete(name = "Job state", labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  labs(title = "Mean time spent in each state for veteran's whole career sequence",
       fill = "Job state",
       caption = "Data: BGT Resumes") +
  ylab("Mean time (years)") +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 40, hjust = 1))

ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/8068),
            size = 2) +
  scale_y_continuous(name = "Share of careers in a job state",
                     sec.axis = sec_axis(trans = ~.*(8068), name = "Number of careers in year of career")) +
  xlim(0,78) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Job states over time for veteran's whole career sequence",
       fill = "Job state",
       caption = "Data: BGT Resumes") +
  theme_classic() +
  theme(legend.position = "bottom")


ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/8068),
            size = 2) +
  scale_y_continuous(name = "Share of careers in a job state",
                     sec.axis = sec_axis(trans = ~.*(8068), name = "Number of careers in year of career")) +
  xlim(0,78) +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2], uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "red", "#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military", "Unemployed")) +
  xlab("Year of career") +
  labs(title = "Job states over time for veteran's whole career sequence",
       fill = "Job state",
       caption = "Data: BGT Resumes") +
  theme_classic() +
  theme(legend.position = "bottom")


ggplot(data = meant, aes(x = state, y = Mean, fill = state)) +
  geom_col() +
  scale_fill_manual(values = c("#CBBEB5",  uva_color_palette[1], uva_color_palette[2],uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "#CBBEB5", "#CBBEB5","#CBBEB5"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Transition unemployed", "Unemployed", "Unemployed/Exit")) +
  scale_x_discrete(name = "Job state", labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Transition unemployed", "Unemployed", "Unemployed/Exit")) +
  labs(title = "Mean time spent in each state for first ten years \n after veteran's last military job",
       fill = "Job state",
       caption = "Data: BGT Resumes") +
  ylab("Mean time (years)") +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 40, hjust = 1))


p <- ggplot() + 
  geom_area(data = states, aes(x = as.numeric(variable), y = value, fill = state, position = "fill")) +
  # geom_line(data = v_states, aes(x = as.numeric(variable), y = v_states/5185),
  #           size = 2) +
  scale_y_continuous(name = "Share of careers in a job state") +
  xlim(0,10) +
  scale_fill_manual(values = c("#CBBEB5", uva_color_palette[1], uva_color_palette[2],uva_color_palette[4],  uva_color_palette[6], uva_color_palette[9], "#DCDCDC", "#C0C0C0", "#696969"), labels = c("Missing zone", "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Military transition unemployed", "Civilian unemployed", "Retired")) +
  xlab("Year of career") +
  labs(title = "Job states over time for first ten years \n after veteran's last military job",
       fill = "Job state",
       caption = "Data: BGT Resumes") +
  theme_classic() +
  theme(legend.position = "bottom")

p +
  scale_x_continuous(breaks = pretty_breaks(4))

```

