---
title: "21_cluster_analysis"
author: "Joanna Schroeder"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE
)
for (pkg in c("tidyverse",  "data.table", "R.utils", "mosaic", "readr", "maditr", "stringr", "stringi", "dplyr", "ggplot2", "lubridate", "gt", "DataExplorer", "TraMineR", "TraMineRextras", "cluster", "tools", "WeightedCluster", "viridis", "splitstackshape")) {
  library(pkg, character.only = TRUE)
}

uva_color_palette <- 
c("#232D4B", #space cadet
  "#2C4F6B", #indigo dye
  "#0E879C", #blue munsell
  "#60999A", #cadet blue
  "#D1E0BF", #tea green
  "#D9E12B", #pear
  "#E6CE3A", #citrine
  "#E6A01D", #marigold
  "#E57200" #princeton orange
)

data_profiling <- function(df){
  nrow = nrow(df)
  summary_table <- tibble(var = names(df),
                          variable_type = map_chr(.x = df, .f = function(col) class(x = col)),                 
                          num_unique = map_int(.x = df, .f = function(col) length(x = unique(x = col))),
                          num_missing = map_int(.x = df, .f = function(col) sum(x = is.na(x = col)))) %>%
    mutate(perc_missing = round(x = 100 * num_missing / nrow, digits = 2L))
  return(summary_table)
}
```

```{r clean-data}
source("~/git/DSPG2020/career/src/burningglass/20_updated_clean_bgt.R")
source("~/git/DSPG2020/career/src/burningglass/master_functions.R")

#bg_cleaned <- get_bgt_data_for_state(states = c("DC", "MD", "VA"))

#bg_covariates <- as.data.table(bg_cleaned$bg_covariates)
#bg_job <- as.data.table(bg_cleaned$bg_job)
#all_majors <- as.data.table(bg_cleaned$all_majors)
#all_skills <- as.data.table(bg_cleaned$all_skills)
#highest_degree_majors <- as.data.table(bg_cleaned$highest_degree_majors)
#top_skills <- as.data.table(bg_cleaned$top_skills)

#write.csv(bg_covariates, file= "~/git/DSPG2020/career/data/testing.csv", row.names = F)
#write.csv(bg_job, file= "~/git/DSPG2020/career/data/bg_job_vadcmd.csv", row.names = F)
#write.csv(all_majors, file= "~/git/DSPG2020/career/data/all_majors_vadcmd.csv", row.names = F)
#write.csv(all_skills, file= "~/git/DSPG2020/career/data/all_skills_vadcmd.csv", row.names = F)
#write.csv(highest_degree_majors, file= "~/git/DSPG2020/career/data/highest_degree_majors_vadcmd.csv", row.names = F)
#write.csv(top_skills, file= "~/git/DSPG2020/career/data/top_skills_vadcmd.csv", row.names = F)

bg_covariates <- fread("~/git/DSPG2020/career/data/bg_covariates_vadcmd.csv")
bg_job <- fread("~/git/DSPG2020/career/data/bg_job_vadcmd.csv")
all_skills <- fread("~/git/DSPG2020/career/data/all_skills_vadcmd.csv")
all_majors <- fread("~/git/DSPG2020/career/data/all_majors_vadcmd.csv")
top_skills <- fread("~/git/DSPG2020/career/data/top_skills_vadcmd.csv")
top_majors <- fread("~/git/DSPG2020/career/data/highest_degree_majors_vadcmd.csv")
archive_covariates <- fread("~/git/DSPG2020/career/data/02_bg_vet_demographic.csv")
archive_job <- fread("~/git/DSPG2020/career/data/03_bg_all_job.csv") %>% select(id, onet_job_zone, start_year, end_year)

year_entered_civilian_workforce <- bg_job %>% left_join(bg_covariates, by = "id") %>%
  mutate(duration = end_year - start_year + 1) %>% group_by(id) %>%
  mutate(aligned_start = min(start_year)) %>% ungroup() %>% filter(onet_job_zone != 55) %>%
  mutate(out = ifelse(veteran == "veteran" & start_year < year_military_exit, 1, 0)) %>%
  group_by(id, out) %>%
  mutate(year_entered_civilian_workforce = min(start_year)) %>% group_by(id) %>%
  mutate(year_entered_civilian_workforce = max(start_year),
         military_transition_unemployment = ifelse((year_entered_civilian_workforce -
                                                     year_military_exit) < 0, 0,
                                                   year_entered_civilian_workforce -
                                                     year_military_exit)) %>%
  select(id, aligned_start, year_entered_civilian_workforce, military_transition_unemployment)

bg_covariates <- bg_covariates %>% select(-aligned_start, -year_entered_civilian_workforce) %>% left_join(year_entered_civilian_workforce, by = "id") %>% distinct()

```

```{r fixing-duplicates}
bg_covariates <- bg_covariates %>%
  mutate(irr_bin = ntile(irr, 5),
         years_in_military_bin = case_when(
        years_in_military >= 1 & years_in_military <= 2 | years_in_military < 0
~ "1 - 2",
years_in_military >= 3 & years_in_military <= 4 ~ "3 - 4",
years_in_military >= 5 & years_in_military <= 10 ~ "5 - 10",
years_in_military >= 11 & years_in_military <= 20 ~ "11 - 20",
years_in_military >= 21 & years_in_military <= 30 ~ "21 - 30",
years_in_military >= 31 ~ "31+"),
year_military_enlist_bin = case_when(
year_military_enlist >= 2001 ~ "2001 or later",
year_military_enlist >= 1990 & year_military_enlist < 2001 ~ "1990 to 2000 (including Persian Gulf War)",
year_military_enlist >= 1975 & year_military_enlist < 1990 ~ "1975 to 1989",
year_military_enlist >= 1964 & year_military_enlist < 1975 ~ "Vietnam era (1964 to 1974)",
year_military_enlist >= 1955 & year_military_enlist < 1964 ~ "1955 to 1963",
year_military_enlist >= 1950 & year_military_enlist < 1955 ~ "Korean war (1950 to 1954)",
year_military_enlist >= 1947 & year_military_enlist < 1950 ~ "1947 to 1949",
year_military_enlist >= 1941 & year_military_enlist < 1947 ~ " World War II (1941 to 1946)",
year_military_enlist < 1941 ~ "1940 or earlier"),
year_entered_workforce_bin = case_when(
aligned_start >= 2017 ~ "Post-Millennial",
aligned_start >= 2001 & aligned_start < 2017 ~ "Millennial",
aligned_start >= 1985 & aligned_start < 2001 ~ "Generation X",
aligned_start >= 1966 & aligned_start < 1985 ~ "Baby Boom",
aligned_start < 1966 ~ "Silent and Greatest"
),
career_before_military_bin = case_when(
career_before_military == 0 ~ "0",
career_before_military >= 1 & career_before_military < 5 ~ "1 - 4",
career_before_military >= 5 & career_before_military < 11 ~ "5 - 10",
career_before_military >= 11 & career_before_military < 21 ~ "11 - 20",
career_before_military >= 21 & career_before_military < 31 ~ "21 - 30",
career_before_military >= 31 ~ "31+"),
military_transition_unemployment_bin = case_when(
military_transition_unemployment == 0 ~ "0",
military_transition_unemployment >= 1 & military_transition_unemployment < 5 ~ "1 - 4",
military_transition_unemployment >= 5 & military_transition_unemployment < 11 ~ "5 - 10",
military_transition_unemployment >= 11 & military_transition_unemployment < 21 ~ "11 - 20",
military_transition_unemployment >= 21 & military_transition_unemployment < 30 ~ "21 - 30",
military_transition_unemployment >= 31 ~ "31+"))
duplicates <- bg_covariates$id[duplicated(bg_covariates$id)]
# Dealing with duplicates
bg_covariates_nodup <- bg_covariates %>% filter(!(id %in% duplicates))
fixed_55 <- bg_covariates %>% filter(id %in% bg_covariates$id[duplicated(bg_covariates$id)]) %>%
mutate(all_other = ifelse(
(end_onet55 == "55-3019.00" | end_onet55 == "55-1019.00"), "all_other", end_onet55))%>% mutate(end_onet55_score = case_when(
all_other != "all_other" ~ 1,
all_other == "all_other" & end_onet55 == "55-1019.00" ~ 2,
all_other == "all_other" & end_onet55 == "55-3019.00" ~ 3)) %>% group_by(id) %>%
mutate(end_onet55_true = ifelse(end_onet55_score == max(end_onet55_score), end_onet55, NA)) %>% drop_na(end_onet55_true) %>% mutate(duplicated = ifelse(duplicated(id) == TRUE, TRUE, FALSE)) %>% filter(duplicated == FALSE) %>% distinct() %>% select(-all_other, -end_onet55_score, -end_onet55_true, -duplicated) %>% filter(id %in% c(218335843, 219487198))
fixed_gender <- bg_covariates %>% filter(id %in% bg_covariates$id[duplicated(bg_covariates$id)]) %>%
mutate(all_other = ifelse(
(end_onet55 == "55-3019.00" | end_onet55 == "55-1019.00"), "all_other", end_onet55))%>% mutate(end_onet55_score = case_when(
all_other != "all_other" ~ 1,
all_other == "all_other" & end_onet55 == "55-1019.00" ~ 2,
all_other == "all_other" & end_onet55 == "55-3019.00" ~ 3)) %>% group_by(id) %>%
mutate(end_onet55_true = ifelse(end_onet55_score == max(end_onet55_score), end_onet55, NA)) %>% drop_na(end_onet55_true) %>% mutate(duplicated = ifelse(duplicated(id) == TRUE, TRUE, FALSE)) %>% filter(duplicated == TRUE) %>% select(-all_other, -end_onet55_score, -end_onet55_true, -duplicated)
bg_covariates <- rbind(bg_covariates_nodup, fixed_55, fixed_gender) %>% distinct()

# STRATIFICATION --------------------------------------
# We are collapsing a few categories: post-bacc becomes bachelors, Post-Millenial becomes Millenial, Silent and Greatest becomes Baby Boom
collapsed <- bg_covariates %>% select(id, veteran, gender, year_entered_workforce_bin, irr_bin, highest_degree) %>% mutate(highest_degree = ifelse(highest_degree == "post-bacc", "bachelors", highest_degree), year_entered_workforce_bin = ifelse(year_entered_workforce_bin == "Post-Millennial", "Millennial", ifelse(year_entered_workforce_bin == "Silent and Greatest", "Baby Boom", year_entered_workforce_bin)))

sample <- collapsed %>% filter(veteran == "not veteran")
stratified <- stratified(sample, c("gender",  "year_entered_workforce_bin", "irr_bin", "highest_degree"), 0.015)
           
table(stratified$gender, stratified$year_entered_workforce_bin, stratified$irr_bin, stratified$highest_degree)

sample %>% mutate(total = n()) %>% group_by(highest_degree) %>% mutate(percent = round(n()/total * 100, 2)) %>% distinct(highest_degree, percent) %>% arrange(-percent)
stratified %>% mutate(total = n()) %>% group_by(gender, irr_bin, year_entered_workforce_bin, highest_degree) %>% mutate(percent = round(n()/total * 100, 2)) %>% distinct(highest_degree, percent) %>% arrange(-percent)

vet_ids <- bg_covariates %>% filter(veteran == "veteran") %>% pull(id)
nonvet_ids <- stratified %>% pull(id)
ids <- c(vet_ids, nonvet_ids)

bg_job_full <- bg_job
bg_covariates_full <- bg_covariates
all_majors_full <- all_majors
top_majors_full <- top_majors
all_skills_full <- all_skills
top_skills_full <- top_skills

bg_job <- bg_job %>% filter(id %in% ids)
bg_covariates <- bg_covariates %>% filter(id %in% ids)
all_majors <- all_majors %>% filter(id %in% ids)
top_majors <- top_majors %>% filter(id %in% ids)
all_skills <- all_skills %>% filter(id %in% ids)
top_skills <- top_skills %>% filter(id %in% ids)

# HIGHEST DEGREE BY INSTITUTION
get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }

#uszips <- fread("~/git/DSPG2020/career/src/burningglass/uszips.csv")
#zips <- uszips %>% filter(state_id %in% c("DC", "MD", "VA")) %>% pull(zip)

con <- get_db_conn()

ed <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.ed WHERE id IN (", paste(ids, collapse = ", "), ")"))
ed <-ed[,1:12]

#job <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.job WHERE id IN (", paste(vet_ids, collapse = ", "), ")")) %>% filter(!is.na(onet) &  !is.na(startdate) & !is.na(enddate))
#job <- job[, 1:9]

DBI::dbDisconnect(con)

forprofit <- fread("~/git/DSPG2020/career/src/burningglass/ipeds_forprofit.csv") %>% pull(UnitID)
hbcu <- fread("~/git/DSPG2020/career/src/burningglass/ipeds_hbcu.csv") %>% pull(UnitID)
tribal <- fread("~/git/DSPG2020/career/src/burningglass/ipeds_tribal.csv") %>% pull(UnitID)

highest_degree_from_forprofit <- ed %>% separate_rows(degreelevel, sep = "#") %>% 
  select(id, degreelevel, ipeds_unit_id) %>% filter(ipeds_unit_id %in% forprofit) %>% group_by(id) %>% mutate(highest_degree_from_forprofit = case_when(
  max(degreelevel, na.rm = TRUE) == 12 ~ "highschool",
  max(degreelevel, na.rm = TRUE) == 13 ~ "GED/diploma",
  max(degreelevel, na.rm = TRUE) == 14 ~ "associates",
  max(degreelevel, na.rm = TRUE) == 16 ~ "bachelors",
  max(degreelevel, na.rm = TRUE) == 17 ~ "post-bacc",
  max(degreelevel, na.rm = TRUE) == 18 ~ "masters",
  max(degreelevel, na.rm = TRUE) == 21 ~ "phd",
  is.na(degreelevel) ~ "missing")) %>% distinct(id, highest_degree_from_forprofit)

highest_degree_from_hbcu <- ed %>% separate_rows(degreelevel, sep = "#") %>% 
  select(id, degreelevel, ipeds_unit_id) %>% filter(ipeds_unit_id %in% hbcu) %>% group_by(id) %>% mutate(highest_degree_from_hbcu = case_when(
    max(degreelevel, na.rm = TRUE) == 12 ~ "highschool",
    max(degreelevel, na.rm = TRUE) == 13 ~ "GED/diploma",
    max(degreelevel, na.rm = TRUE) == 14 ~ "associates",
    max(degreelevel, na.rm = TRUE) == 16 ~ "bachelors",
    max(degreelevel, na.rm = TRUE) == 17 ~ "post-bacc",
    max(degreelevel, na.rm = TRUE) == 18 ~ "masters",
    max(degreelevel, na.rm = TRUE) == 21 ~ "phd",
    is.na(degreelevel) ~ "missing")) %>% distinct(id, highest_degree_from_hbcu)


highest_degree_from_forprofit$id <- as.character(highest_degree_from_forprofit$id)
highest_degree_from_hbcu$id <- as.character(highest_degree_from_hbcu$id)

bg_covariates %>% filter(veteran == "veteran") %>% 
  mutate(years_experience = year_entered_civilian_workforce - aligned_start) %>% group_by(years_experience) %>% mutate(count = n()) %>% distinct(years_experience, count) %>%
  ggplot(aes(x = years_experience, y = count)) +
  geom_area()

bg_covariates %>% filter(veteran == "veteran") %>% 
  mutate(years_experience = year_entered_civilian_workforce - aligned_start) %>% summarise(median = median(years_experience, na.rm = TRUE))

all_ids <- bg_covariates$id

dataset_all_majors <- all_majors %>% filter(id %in% all_ids) %>% filter(!duplicated(id)) %>%
  rename("health_professions" = "51", "social_sciences" = "45", "business" = "52", "computer" = "11", "public_administration" = "44", "visual_arts" = "50", "engineering_tech" = "15", "biology" = "26", "humanities" = "24", "communication" = "09", "engineering" = "14", "philosophy_religion" = "38", "psychology" = "42", "homeland_security" = "43", "physics" = "40", "family_consumer" = "19", "theology_religion" = "39", "culinary_entertainment" = "12", "language_linguistics" = "16", "mathematics" = "27", "education" = "13", "recreation_kinesiology" = "31", "english" = "23", "cultural_gender" = "05", "law" = "22", "agriculture_veterinary" = "01", "leisure_recreation" = "36", "construction" = "46", "library" = "25", "natural_resource" = "03", "architecture" = "04", "interdisciplinary" = "30", "communication_tech" = "10", "transportation_materials" = "49", "health_residency" = "60", "military_science" = "28", "mechanic_repair" = "47", "science_tech" = "41", "military_tech" = "29")
dataset_top_majors <- top_majors %>% filter(id %in% all_ids) %>% filter(!duplicated(id)) %>% select(-"NA") %>%
  rename("health_professions" = "51", "social_sciences" = "45", "business" = "52", "computer" = "11", "public_administration" = "44", "visual_arts" = "50", "engineering_tech" = "15", "biology" = "26", "humanities" = "24", "communication" = "09", "engineering" = "14", "philosophy_religion" = "38", "psychology" = "42", "homeland_security" = "43", "physics" = "40", "family_consumer" = "19", "theology_religion" = "39", "culinary_entertainment" = "12", "language_linguistics" = "16", "mathematics" = "27", "education" = "13", "recreation_kinesiology" = "31", "english" = "23", "cultural_gender" = "05", "law" = "22", "agriculture_veterinary" = "01", "leisure_recreation" = "36", "construction" = "46", "library" = "25", "natural_resource" = "03", "architecture" = "04", "interdisciplinary" = "30", "communication_tech" = "10", "transportation_materials" = "49", "health_residency" = "60", "military_science" = "28", "mechanic_repair" = "47", "science_tech" = "41", "military_tech" = "29") %>% pivot_longer(cols = `health_professions`:`military_tech`) %>% filter(value == 1) %>% distinct(id, "top_major" = name)
dataset_all_skills <- all_skills %>% filter(id %in% all_ids) %>% filter(!duplicated(id)) %>%
  rename("information" = "Information Technology", "supply" = "Supply Chain and Logistics", "sales" = "Sales", "business" = "Business", "manufacturing" = "Manufacturing and Production", "environment" = "Environment", "design" = "Design", "administration" = "Administration", "customer" = "Customer and Client Support", "analysis" = "Analysis", "finance" = "Finance", "personal" = "Personal Care and Services", "legal" = "Legal", "education" = "Education and Training", "health" = "Health Care", "science" = "Science and Research", "human" = "Human Resources", "marketing" = "Marketing and Public Relations", "energy" = "Energy and Utilities", "economics" = "Economics, Policy, and Social Studies", "media" = "Media and Writing", "engineering" = "Engineering", "maintenance" = "Maintenance, Repair, and Installation", "agriculture" = "Agriculture, Horticulture, and the Outdoors", "architecture" = "Architecture and Construction", "industry" = "Industry Knowledge", "security" = "Public Safety and National Security", "religion" = "Religion")
dataset_top_skills <- top_skills %>% filter(id %in% all_ids) %>% filter(!duplicated(id)) %>%
  rename("information" = "Information Technology", "supply" = "Supply Chain and Logistics", "sales" = "Sales", "business" = "Business", "manufacturing" = "Manufacturing and Production", "environment" = "Environment", "design" = "Design", "administration" = "Administration", "customer" = "Customer and Client Support", "analysis" = "Analysis", "finance" = "Finance", "personal" = "Personal Care and Services", "legal" = "Legal", "education" = "Education and Training", "health" = "Health Care", "science" = "Science and Research", "human" = "Human Resources", "marketing" = "Marketing and Public Relations", "energy" = "Energy and Utilities", "economics" = "Economics, Policy, and Social Studies", "media" = "Media and Writing", "engineering" = "Engineering", "maintenance" = "Maintenance, Repair, and Installation", "agriculture" = "Agriculture, Horticulture, and the Outdoors", "architecture" = "Architecture and Construction", "industry" = "Industry Knowledge", "security" = "Public Safety and National Security", "religion" = "Religion") %>% pivot_longer(cols = `information`:`religion`) %>% filter(value == 1) %>% distinct(id, "top_skill" = name)
all_ids <- as.integer(all_ids)

ids <- dataset_all_majors$id
missing_all_majors_ids <- as.data.frame(all_ids) %>% rename(id = all_ids) %>% filter(!(id %in% ids))
dataset_all_majors <- dataset_all_majors %>% rbind(missing_all_majors_ids, fill = TRUE)

ids <- dataset_top_majors$id
missing_top_majors_ids <- as.data.frame(all_ids) %>% rename(id = all_ids) %>% filter(!(id %in% ids)) %>% mutate(top_major = NA)
dataset_top_majors <- dataset_top_majors %>% rbind(missing_top_majors_ids)

ids <- dataset_all_skills$id
missing_all_skills_ids <- as.data.frame(all_ids) %>% rename(id = all_ids) %>% filter(!(id %in% ids))
dataset_all_skills <- dataset_all_skills %>% rbind(missing_all_skills_ids, fill = TRUE)

ids <- dataset_top_skills$id
missing_top_skills_ids <- as.data.frame(all_ids) %>% rename(id = all_ids) %>% filter(!(id %in% ids)) %>% mutate(top_skill = NA)
dataset_top_skills <- dataset_top_skills %>% rbind(missing_top_skills_ids)
```

```{r clustering-metrics, fig.height=10, fig.width=15}
#seq.10 <- create_seq_all_fixed("seq.10", 10, left_unemp = FALSE)
#seq.20 <- create_seq_all_fixed("seq.20", 20, left_unemp = FALSE)
#seq.30 <- create_seq_all_fixed("seq.30", 30, left_unemp = FALSE)

## TEN YEARS
transition_matrix <- seqtrate(seq.10, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

# OPTION 1 : OUR OM SPELL, LOW EXPANSION COST AND LOW WEIGHT
sequencing.opt1 <- seqdist(seq.10, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)

# OPTION 2 : OUR OM
sequencing.opt2 <- seqdist(seq.10, method = "OMstran", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0.5)

# OPTION 3 : OUR OM, LOW WEIGHT ON ORIGIN
sequencing.opt3 <- seqdist(seq.10, method = "OMstran", indel = 1, sm = cost_matrix, with.missing = TRUE, otto = 0.01)

# CLUSTERING
numbers <- (2:20)
pamstats <- NULL
#rownames(pamstats) <- numbers
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt1, k = number)
  assign(paste0("sequencing.pam.opt1.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt1 <- dplyr::bind_rows(pamstats)
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt2, k = number)
  assign(paste0("sequencing.pam.opt2.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt2 <- dplyr::bind_rows(pamstats)
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt3, k = number)
  assign(paste0("sequencing.pam.opt3.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt3 <- dplyr::bind_rows(pamstats)

# QUALITY METRICS
rownames(pamstats.opt1) <- numbers
PAM.ASW.Opt1 <- as.matrix(pamstats.opt1$ASW)
colnames(PAM.ASW.Opt1) <- c("ASW opt1")
PAM.ASW.Opt2 <- as.matrix(pamstats.opt2$ASW)
colnames(PAM.ASW.Opt2) <- c("ASW opt2")
PAM.ASW.Opt3 <- as.matrix(pamstats.opt3$ASW)
colnames(PAM.ASW.Opt3) <- c("ASW opt3")
PAM.ASW <- bind_cols(PAM.ASW.Opt1, PAM.ASW.Opt2, PAM.ASW.Opt3)
PAM.ASW <- PAM.ASW %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.ASW$rowname <- as.numeric(PAM.ASW$rowname)

rownames(pamstats.opt1) <- numbers
PAM.HC.Opt1 <- as.matrix(pamstats.opt1$HC)
colnames(PAM.HC.Opt1) <- c("HC opt1")
PAM.HC.Opt2 <- as.matrix(pamstats.opt2$HC)
colnames(PAM.HC.Opt2) <- c("HC opt2")
PAM.HC.Opt3 <- as.matrix(pamstats.opt3$HC)
colnames(PAM.HC.Opt3) <- c("HC opt3")
PAM.HC <- bind_cols(PAM.HC.Opt1, PAM.HC.Opt2, PAM.HC.Opt3)
PAM.HC <- PAM.HC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.HC$rowname <- as.numeric(PAM.HC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.PBC.Opt1 <- as.matrix(pamstats.opt1$PBC)
colnames(PAM.PBC.Opt1) <- c("PBC opt1")
PAM.PBC.Opt2 <- as.matrix(pamstats.opt2$PBC)
colnames(PAM.PBC.Opt2) <- c("PBC opt2")
PAM.PBC.Opt3 <- as.matrix(pamstats.opt3$PBC)
colnames(PAM.PBC.Opt3) <- c("PBC opt3")
PAM.PBC <- bind_cols(PAM.PBC.Opt1, PAM.PBC.Opt2, PAM.PBC.Opt3)
PAM.PBC <- PAM.PBC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.PBC$rowname <- as.numeric(PAM.PBC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.R2.Opt1 <- as.matrix(pamstats.opt1$R2)
colnames(PAM.R2.Opt1) <- c("R2 opt1")
PAM.R2.Opt2 <- as.matrix(pamstats.opt2$R2)
colnames(PAM.R2.Opt2) <- c("R2 opt2")
PAM.R2.Opt3 <- as.matrix(pamstats.opt3$R2)
colnames(PAM.R2.Opt3) <- c("R2 opt3")
PAM.R2 <- bind_cols(PAM.R2.Opt1, PAM.R2.Opt2, PAM.R2.Opt3)
PAM.R2 <- PAM.R2 %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.R2$rowname <- as.numeric(PAM.R2$rowname)

PAM.ASW %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.HC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.PBC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.R2 %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

## TWENTY YEARS
transition_matrix <- seqtrate(seq.20, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

# OPTION 1 : OUR OM SPELL, LOW EXPANSION COST AND LOW WEIGHT
sequencing.opt1 <- seqdist(seq.20, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)

# OPTION 2 : OUR OM
sequencing.opt2 <- seqdist(seq.20, method = "OMstran", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0.5)

# OPTION 3 : OUR OM, LOW WEIGHT ON ORIGIN
sequencing.opt3 <- seqdist(seq.20, method = "OMstran", indel = 1, sm = cost_matrix, with.missing = TRUE, otto = 0.01)

# CLUSTERING
numbers <- (2:20)
pamstats <- NULL
#rownames(pamstats) <- numbers
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt1, k = number)
  assign(paste0("sequencing.pam.opt1.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt1 <- dplyr::bind_rows(pamstats)
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt2, k = number)
  assign(paste0("sequencing.pam.opt2.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt2 <- dplyr::bind_rows(pamstats)
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt3, k = number)
  assign(paste0("sequencing.pam.opt3.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt3 <- dplyr::bind_rows(pamstats)

# QUALITY METRICS
rownames(pamstats.opt1) <- numbers
PAM.ASW.Opt1 <- as.matrix(pamstats.opt1$ASW)
colnames(PAM.ASW.Opt1) <- c("ASW opt1")
PAM.ASW.Opt2 <- as.matrix(pamstats.opt2$ASW)
colnames(PAM.ASW.Opt2) <- c("ASW opt2")
PAM.ASW.Opt3 <- as.matrix(pamstats.opt3$ASW)
colnames(PAM.ASW.Opt3) <- c("ASW opt3")
PAM.ASW <- bind_cols(PAM.ASW.Opt1, PAM.ASW.Opt2, PAM.ASW.Opt3)
PAM.ASW <- PAM.ASW %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.ASW$rowname <- as.numeric(PAM.ASW$rowname)

rownames(pamstats.opt1) <- numbers
PAM.HC.Opt1 <- as.matrix(pamstats.opt1$HC)
colnames(PAM.HC.Opt1) <- c("HC opt1")
PAM.HC.Opt2 <- as.matrix(pamstats.opt2$HC)
colnames(PAM.HC.Opt2) <- c("HC opt2")
PAM.HC.Opt3 <- as.matrix(pamstats.opt3$HC)
colnames(PAM.HC.Opt3) <- c("HC opt3")
PAM.HC <- bind_cols(PAM.HC.Opt1, PAM.HC.Opt2, PAM.HC.Opt3)
PAM.HC <- PAM.HC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.HC$rowname <- as.numeric(PAM.HC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.PBC.Opt1 <- as.matrix(pamstats.opt1$PBC)
colnames(PAM.PBC.Opt1) <- c("PBC opt1")
PAM.PBC.Opt2 <- as.matrix(pamstats.opt2$PBC)
colnames(PAM.PBC.Opt2) <- c("PBC opt2")
PAM.PBC.Opt3 <- as.matrix(pamstats.opt3$PBC)
colnames(PAM.PBC.Opt3) <- c("PBC opt3")
PAM.PBC <- bind_cols(PAM.PBC.Opt1, PAM.PBC.Opt2, PAM.PBC.Opt3)
PAM.PBC <- PAM.PBC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.PBC$rowname <- as.numeric(PAM.PBC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.R2.Opt1 <- as.matrix(pamstats.opt1$R2)
colnames(PAM.R2.Opt1) <- c("R2 opt1")
PAM.R2.Opt2 <- as.matrix(pamstats.opt2$R2)
colnames(PAM.R2.Opt2) <- c("R2 opt2")
PAM.R2.Opt3 <- as.matrix(pamstats.opt3$R2)
colnames(PAM.R2.Opt3) <- c("R2 opt3")
PAM.R2 <- bind_cols(PAM.R2.Opt1, PAM.R2.Opt2, PAM.R2.Opt3)
PAM.R2 <- PAM.R2 %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.R2$rowname <- as.numeric(PAM.R2$rowname)

PAM.ASW %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.HC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.PBC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.R2 %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

## THIRTY YEARS -----------------
transition_matrix <- seqtrate(seq.30, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

# OPTION 1 : OUR OM SPELL, LOW EXPANSION COST AND LOW WEIGHT
sequencing.opt1 <- seqdist(seq.30, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)

# OPTION 2 : OUR OM
sequencing.opt2 <- seqdist(seq.30, method = "OMstran", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0.5)

# OPTION 3 : OUR OM, LOW WEIGHT ON ORIGIN
sequencing.opt3 <- seqdist(seq.30, method = "OMstran", indel = 1, sm = cost_matrix, with.missing = TRUE, otto = 0.01)

# CLUSTERING
numbers <- (2:20)
pamstats <- NULL
#rownames(pamstats) <- numbers
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt1, k = number)
  assign(paste0("sequencing.pam.opt1.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt1 <- dplyr::bind_rows(pamstats)
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt2, k = number)
  assign(paste0("sequencing.pam.opt2.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt2 <- dplyr::bind_rows(pamstats)
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt3, k = number)
  assign(paste0("sequencing.pam.opt3.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt3 <- dplyr::bind_rows(pamstats)

# QUALITY METRICS
rownames(pamstats.opt1) <- numbers
PAM.ASW.Opt1 <- as.matrix(pamstats.opt1$ASW)
colnames(PAM.ASW.Opt1) <- c("ASW opt1")
PAM.ASW.Opt2 <- as.matrix(pamstats.opt2$ASW)
colnames(PAM.ASW.Opt2) <- c("ASW opt2")
PAM.ASW.Opt3 <- as.matrix(pamstats.opt3$ASW)
colnames(PAM.ASW.Opt3) <- c("ASW opt3")
PAM.ASW <- bind_cols(PAM.ASW.Opt1, PAM.ASW.Opt2, PAM.ASW.Opt3)
PAM.ASW <- PAM.ASW %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.ASW$rowname <- as.numeric(PAM.ASW$rowname)

rownames(pamstats.opt1) <- numbers
PAM.HC.Opt1 <- as.matrix(pamstats.opt1$HC)
colnames(PAM.HC.Opt1) <- c("HC opt1")
PAM.HC.Opt2 <- as.matrix(pamstats.opt2$HC)
colnames(PAM.HC.Opt2) <- c("HC opt2")
PAM.HC.Opt3 <- as.matrix(pamstats.opt3$HC)
colnames(PAM.HC.Opt3) <- c("HC opt3")
PAM.HC <- bind_cols(PAM.HC.Opt1, PAM.HC.Opt2, PAM.HC.Opt3)
PAM.HC <- PAM.HC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.HC$rowname <- as.numeric(PAM.HC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.PBC.Opt1 <- as.matrix(pamstats.opt1$PBC)
colnames(PAM.PBC.Opt1) <- c("PBC opt1")
PAM.PBC.Opt2 <- as.matrix(pamstats.opt2$PBC)
colnames(PAM.PBC.Opt2) <- c("PBC opt2")
PAM.PBC.Opt3 <- as.matrix(pamstats.opt3$PBC)
colnames(PAM.PBC.Opt3) <- c("PBC opt3")
PAM.PBC <- bind_cols(PAM.PBC.Opt1, PAM.PBC.Opt2, PAM.PBC.Opt3)
PAM.PBC <- PAM.PBC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.PBC$rowname <- as.numeric(PAM.PBC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.R2.Opt1 <- as.matrix(pamstats.opt1$R2)
colnames(PAM.R2.Opt1) <- c("R2 opt1")
PAM.R2.Opt2 <- as.matrix(pamstats.opt2$R2)
colnames(PAM.R2.Opt2) <- c("R2 opt2")
PAM.R2.Opt3 <- as.matrix(pamstats.opt3$R2)
colnames(PAM.R2.Opt3) <- c("R2 opt3")
PAM.R2 <- bind_cols(PAM.R2.Opt1, PAM.R2.Opt2, PAM.R2.Opt3)
PAM.R2 <- PAM.R2 %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.R2$rowname <- as.numeric(PAM.R2$rowname)

PAM.ASW %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.HC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.PBC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.R2 %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()


## HIGH PERFORMERS:
## 10 YEARS: OPT 3 19-20, OPT 2 5, OPT 1 19-20
## 20 YEARS: OPT 2 6, OPT 2 19-20
## 30 YEARS: OPT 5, OPT 2 19-20
```

```{r cluster-function}
cluster <- function(name, object, sequence_option = "option 1", cluster_number) {
transition_matrix <- seqtrate(object, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

if (sequence_option == "option 1"){
# OPTION 1 : OUR OM SPELL, LOW EXPANSION COST AND LOW WEIGHT
sequencing <- seqdist(object, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)
}
if (sequence_option == "option 2"){
# OPTION 2 : OUR OM
sequencing <- seqdist(object, method = "OMstran", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0.5)
}
if (sequence_option == "option 3"){
# OPTION 3 : OUR OM, LOW WEIGHT ON ORIGIN
sequencing <- seqdist(object, method = "OMstran", indel = 1, sm = cost_matrix, with.missing = TRUE, otto = 0.01)
}
clusterpam <- wcKMedoids(sequencing, k = cluster_number)
#clusterpam$stats

#clusterpam <- clusterpam$clustering
#clusterpam <- factor(clusterpam)

cluster <- list(sequencing, clusterpam)
names(cluster) <- c("diss", "cluster")

assign(name, cluster, envir = .GlobalEnv)
}

cluster_membership_visualization <- function(variable) {
  overall <- all_df %>% filter(!is.na({{ variable }})) %>% mutate(total = n()) %>% group_by(cluster) %>% mutate(overall_cluster_count = n()) %>% group_by({{ variable }}) %>% mutate(overall_covariate_percent = round((n()/total * 100), 2)) %>% distinct({{ variable }}, overall_covariate_percent) %>% mutate(cluster_label = "overall", cluster_group = "overall", overall_cluster_percent = .1) %>% rename(cluster_covariate_percent = overall_covariate_percent)
all_df %>% filter(!is.na({{ variable }})) %>% mutate(total = n()) %>% group_by(cluster) %>% mutate(overall_cluster_count = n(), overall_cluster_percent = n()/total) %>% group_by({{ variable }}) %>% mutate(overall_covariate_percent = round((n()/total * 100), 2)) %>% group_by(cluster, {{ variable }}) %>% mutate(cluster_covariate_percent = round((n()/overall_cluster_count * 100), 2)) %>% distinct(cluster, cluster_label, cluster_group, {{ variable }}, cluster_covariate_percent, overall_cluster_percent) %>% rbind(overall) %>%
  ggplot(aes(cluster_covariate_percent, cluster_label, fill = factor({{ variable }}))) +
  geom_col(aes(width = overall_cluster_percent*10)) +
  facet_wrap(~ factor(cluster_group, levels = c("overall", "education", "promotion", "no change", "demotion", "unemployment")), ncol = 1, scales="free")
}
```

Final clustering:
- Veterans and nonveterans and all
- 10, 20, 30 years

HIGH PERFORMERS:
10 YEARS: OPT 3 19-20, OPT 2 5, OPT 1 19-20
20 YEARS: OPT 2 6, OPT 2 19-20
30 YEARS: OPT 2 5, OPT 2 19-20

```{r creating-all-clusters, fig.height=10, fig.width=15}
# NO YEARS EXPERIENCE ------------------------------------------------------------------------
# Creating sequence objects fo 10, 20, and 30 years
seq.10 <- create_seq_all_fixed("seq.10", 10, left_unemp = FALSE, 0)
seq.20 <- create_seq_all_fixed("seq.20", 20, left_unemp = FALSE, 0)
seq.30 <- create_seq_all_fixed("seq.30", 30, left_unemp = FALSE, 0)

# Clustering sequnces
seq.10cluster_20 <- cluster("cluster_10", seq.10, sequence_option = "option 1", 20)
seq.20cluster_20 <- cluster("cluster_10", seq.20, sequence_option = "option 2", 20)
seq.30cluster_10 <- cluster("cluster_10", seq.30, sequence_option = "option 2", 10)
```

```{r all-clusters-ten-years, fig.height=10, fig.width=15}
# Visualizing 10 years 20 cluster solution --------------------------------------------------
seq.10cluster_20$cluster$stats

cluster_20 <- seq.10cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(4978, 7021, 7022, 7071, 7076, 7122, 7129) ~ "education",
cluster %in% c(9824, 14775, 14784, 16067) ~ "promotion",
cluster %in% c(9986, 14768) ~ "demotion",
cluster %in% c(9980, 10176, 14662, 16075) ~ "unemployment",
cluster %in% c(14786, 16082, 16620) ~ "no change"
),
cluster_label = case_when(
  cluster == 4978 ~ "education to unemployment to education",
  cluster == 7021 ~ "education to zone 5",
  cluster == 7022 ~ "education to zone 4",
  cluster == 7071 ~ "education to zone 3",
  cluster == 7076 ~ "education to unemployment",
  cluster == 7122 ~ "zone 4 to education to zone 4",
  cluster == 7129 ~ "education to unemployment to zone 4",
  cluster == 9824 ~ "zone 4 to zone 5",
  cluster == 9980 ~ "zone 5 to unemployment",
  cluster == 9986 ~ "zone 5 to zone 4",
  cluster == 10176 ~ "zone 2 to unemployment to zone 2",
  cluster == 14662 ~ "zone 4 to unemployment to zone 4",
  cluster == 14768 ~ "zone 4 to zone 3",
  cluster == 14775 ~ "zone 2 to zone 4",
  cluster == 14784 ~ "zone 3 to zone 4",
  cluster == 14786 ~ "zone 4",
  cluster == 16067 ~ "zone 2 to zone 3",
  cluster == 16075 ~ "zone 3 to unemployment to zone 3",
  cluster == 16082 ~ "zone 3",
  cluster == 16620 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
seqrplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.10cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
ggplot(veteran, aes(cluster_label, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by veteran") +
  facet_grid(rows = vars(cluster_group))

cluster_membership_visualization(veteran)
cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)
cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)
```

```{r all-clusters-twenty-years, fig.height=10, fig.width=15}
# Visualizing 20 years 20 cluster solution --------------------------------------------------
seq.20cluster_20$cluster$stats

cluster_20 <- seq.20cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(67, 647, 1485, 1527, 1558, 1667, 2500, 2711, 3165) ~ "education",
cluster %in% c(4580, 4583, 4615, 5905, 6797) ~ "promotion",
cluster %in% c(5776) ~ "demotion",
cluster %in% c(3830) ~ "unemployment",
cluster %in% c(3713, 6524, 6944, 7058) ~ "no change"
),
cluster_label = case_when(
  cluster == 67 ~ "education to zone 4 (Late career)",
  cluster == 647 ~ "education to zone 5",
  cluster == 1485 ~ "education to unemployment to education",
  cluster == 1527 ~ "education to unemployment to zone 2",
  cluster == 1558 ~ "education to zone 3",
  cluster == 1667 ~ "education to zone 4 to education",
  cluster == 2500 ~ "education to unemployment to zone 4",
  cluster == 2711 ~ "education to unemployment",
  cluster == 3165 ~ "education to zone 4 (Early career)",
  cluster == 3713 ~ "zone 4 to zone 5 to zone 4",
  cluster == 3830 ~ "zone 4 to unemployment",
  cluster == 4580 ~ "zone 4 to zone 5 (Early career)",
  cluster == 4583 ~ "zone 4 to zone 5 (Late career)",
  cluster == 4615 ~ "zone 3 to zone 4",
  cluster == 5776 ~ "zone 4 to zone 3",
  cluster == 5905 ~ "zone 2 to zone 4",
  cluster == 6524 ~ "zone 4",
  cluster == 6797 ~ "zone 2 to zone 3",
  cluster == 6944 ~ "zone 3",
  cluster == 7058 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
seqrplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.20cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
ggplot(veteran, aes(cluster_label, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by veteran") +
  facet_grid(rows = vars(cluster_group))

cluster_membership_visualization(veteran)
cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)
cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)
```

```{r all-clusters-thirty-years, fig.height=10, fig.width=15}
# Visualizing 30 years 10 cluster solution --------------------------------------------------
seq.30cluster_10$cluster$stats

cluster_20 <- seq.30cluster_10$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(114, 168, 259, 836, 929, 1027) ~ "education",
cluster %in% c(1710) ~ "promotion",
#cluster %in% c(4200) ~ "demotion",
#cluster %in% c() ~ "unemployment",
cluster %in% c(2086, 2184, 2203) ~ "no change"
),
cluster_label = case_when(
  cluster == 114 ~ "education to unemployment to zone 4",
  cluster == 168 ~ "education to unemployment",
  cluster == 259 ~ "education to zone 4",
  cluster == 836 ~ "education to unemployment to zone 2",
  cluster == 929 ~ "education/zone 4 to zone 5",
  cluster == 1027 ~ "education to unemployment to zone 3",
  cluster == 1710 ~ "zone 3 to zone 4",
  cluster == 2086 ~ "zone 4",
  cluster == 2184 ~ "zone 3",
  cluster == 2203 ~ "zone 2",
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.30, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
seqrplot(seq.30, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.30cluster_10$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
ggplot(veteran, aes(cluster_label, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by veteran") +
  facet_grid(rows = vars(cluster_group))

cluster_membership_visualization(veteran)
cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)
cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)
```

```{r creating-all-clusters-yexp, fig.height=10, fig.width=15}
# 15 YEARS EXPERIENCE ------------------------------------------------------------------------
# Creating sequence objects fo 10, 20, and 30 years
seq.10 <- create_seq_all_fixed("seq.10", 10, left_unemp = FALSE, 15)
seq.20 <- create_seq_all_fixed("seq.20", 20, left_unemp = FALSE, 15)
seq.30 <- create_seq_all_fixed("seq.30", 30, left_unemp = FALSE, 15)

# Clustering sequnces
seq.10cluster_20 <- cluster("cluster_10", seq.10, sequence_option = "option 1", 20)
seq.20cluster_20 <- cluster("cluster_10", seq.20, sequence_option = "option 2", 20)
seq.30cluster_8 <- cluster("cluster_10", seq.30, sequence_option = "option 2", 8)
```

```{r all-clusters-yexp-ten-years, fig.height=10, fig.width=15}
# Visualizing 10 years 20 cluster solution --------------------------------------------------
seq.10cluster_20$cluster$stats

cluster_20 <- seq.10cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(1698, 2062, 2098, 2163) ~ "education",
cluster %in% c(4122, 7024, 7033, 7647) ~ "promotion",
cluster %in% c(4139, 7017) ~ "demotion",
cluster %in% c(6798, 6998, 7628, 7662) ~ "unemployment",
cluster %in% c(4133, 4142, 7000, 7035, 7662, 7937) ~ "no change"
),
cluster_label = case_when(
  cluster == 1698 ~ "zone 4 to education",
  cluster == 2062 ~ "education to zone 5",
  cluster == 2098 ~ "education to zone 4",
  cluster == 2163 ~ "zone 4 to education to zone 4",
  cluster == 4122 ~ "zone 4 to zone 5",
  cluster == 4133 ~ "zone 5",
  cluster == 4139 ~ "zone 5 to zone 4",
  cluster == 4142 ~ "zone 4 to zone 5 to zone 4",
  cluster == 6798 ~ "zone 4 to unemployment to zone 4",
  cluster == 6998 ~ "zone 4 to unemployment",
  cluster == 7000 ~ "zone 4 to zone 3 to zone 4",
  cluster == 7017 ~ "zone 4 to zone 3",
  cluster == 7024 ~ "zone 2 to zone 4",
  cluster == 7033 ~ "zone 3 to zone 4",
  cluster == 7035 ~ "zone 4",
  cluster == 7628 ~ "zone 3 to unemployment to zone 3",
  cluster == 7647 ~ "zone 2 to zone 3",
  cluster == 7662 ~ "zone 3",
  cluster == 7936 ~ "zone 2 to unemployment",
  cluster == 7937 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
seqrplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.10cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
ggplot(veteran, aes(cluster_label, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by veteran") +
  facet_grid(rows = vars(cluster_group))

cluster_membership_visualization(veteran)
cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)
cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)
```

```{r all-clusters-yexp-twenty-years, fig.height=10, fig.width=15}
# Visualizing 20 years 20 cluster solution --------------------------------------------------
seq.20cluster_20$cluster$stats

cluster_20 <- seq.20cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(117, 399, 688, 705) ~ "education",
cluster %in% c(863, 1511, 2139, 2291, 2421) ~ "promotion",
cluster %in% c(868, 935, 1710,  2154) ~ "demotion",
cluster %in% c(1817, 2241) ~ "unemployment",
cluster %in% c(1336, 1518, 2418, 2252, 2612) ~ "no change"
),
cluster_label = case_when(
  cluster == 117 ~ "education to long unemployment to zone 4",
  cluster == 399 ~ "zone 4 to education to zone 4",
  cluster == 688 ~ "education to zone 4",
  cluster == 705 ~ "education to zone 5",
  cluster == 863 ~ "zone 4 to zone 5 (Early career)",
  cluster == 868 ~ "zone 5 to zone 4 (Early career)",
  cluster == 935 ~ "zone 5 to zone 4 (Late career)",
  cluster == 1336 ~ "zone 4 to zone 5 to zone 4",
  cluster == 1511 ~ "zone 4 to zone 5 (Late career)",
  cluster == 1518 ~ "zone 5",
  cluster == 1710 ~ "zone 4 to zone 2",
  cluster == 1817 ~ "zone 4 to unemployment",
  cluster == 2139 ~ "zone 3 to zone 4",
  cluster == 2154 ~ "zone 4 to zone 3",
  cluster == 2241 ~ "zone 4 to unemployment to zone 4",
  cluster == 2291 ~ "zone 2 to zone 4",
  cluster == 2418 ~ "zone 4",
  cluster == 2421 ~ "zone 2 to zone 3",
  cluster == 2252 ~ "zone 3",
  cluster == 2612 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
seqrplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.20cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
ggplot(veteran, aes(cluster_label, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by veteran") +
  facet_grid(rows = vars(cluster_group))

cluster_membership_visualization(veteran)
cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)
```

```{r all-clusters-cohort, fig.height=10, fig.width=15}
# APPROXIMATE AGE ---------------------------------------------------------------
# Cohort clustering whole career ------------------------------------------------
seq.10 <- create_seq_all_cohort("seq.10", 2000, 2005, after_military = FALSE, left_unemp = FALSE)
seq.10cluster_20 <- cluster("cluster_10", seq.10, sequence_option = "option 1", 20)

cluster_20 <- seq.10cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(2791, 6868, 6884, 6885, 6888) ~ "education",
cluster %in% c(8748, 14400, 14430, 16736) ~ "promotion",
cluster %in% c(8741, 14409, 14414) ~ "demotion",
cluster %in% c(14053) ~ "unemployment",
cluster %in% c(2830, 2831, 6883, 8743, 14435, 16744, 18571) ~ "no change"
),
cluster_label = case_when(
  cluster == 2791 ~ "education to military",
  cluster == 2830 ~ "military",
  cluster == 2831 ~ "military to zone 4",
  cluster == 6868 ~ "education to zone 4",
  cluster == 6883 ~ "zone 4 to education to military/zone 2",
  cluster == 6884 ~ "education to zone 3",
  cluster == 6885 ~ "education to zone 2",
  cluster == 6888 ~ "education to zone 5",
  cluster == 8741 ~ "zone 5 to zone 4",
  cluster == 8743 ~ "zone 5",
  cluster == 8748 ~ "zone 4 to zone 5",
  cluster == 14053 ~ "unemployment to zone 4",
  cluster == 14400 ~ "zone 2 to zone 4",
  cluster == 14409 ~ "zone 4 to zone 3",
  cluster == 14414 ~ "zone 4 to zone 2",
  cluster == 14430 ~ "zone 3 to zone 4",
  cluster == 14435 ~ "zone 4",
  cluster == 16736 ~ "zone 2 to zone 3",
  cluster == 16744 ~ "zone 3",
  cluster == 18571 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))


seq.10 <- seq.10[,1:20]
seqdplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", axes = c(1,20), 
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "red", "#CBBEB5"))
seqrplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.10cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

cluster_membership_visualization(veteran)
```

```{r all-clusters-five-years-exp, fig.height=10, fig.width=15}
# Filtering for five years of experience and careers of 10 years ----------------------------------
seq.10 <- create_seq_all_fixed_experience("seq.10", 10, left_unemp = FALSE, 5)
seq.10cluster_20 <- cluster("cluster_10", seq.10, sequence_option = "option 1", 20)

cluster_20 <- seq.10cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(3140, 3148, 3191, 3212) ~ "education",
cluster %in% c(5016, 8681, 8684, 9682) ~ "promotion",
cluster %in% c(5053, 8641) ~ "demotion",
cluster %in% c(8523, 8670, 9664, 10161) ~ "unemployment",
cluster %in% c(5074, 5078, 8310, 8675, 9682, 10156) ~ "no change"
),
cluster_label = case_when(
  cluster == 3140 ~ "education to zone 4",
  cluster == 3148 ~ "education to unemployment",
  cluster == 3191 ~ "zone 4 to education to zone 4",
  cluster == 3212 ~ "education to zone 5",
  cluster == 5016 ~ "zone 4 to zone 5",
  cluster == 5053 ~ "zone 5 to zone 4",
  cluster == 5074 ~ "zone 5",
  cluster == 5078 ~ "zone 4 to zone 5 to zone 4",
  cluster == 8310 ~ "zone 4",
  cluster == 8523 ~ "zone 4 to unemployment to zone 4",
  cluster == 8641 ~ "zone 4 to zone 3",
  cluster == 8670 ~ "zone 4 to unemployment",
  cluster == 8675 ~ "zone 4 to zone 3 to zone 4",
  cluster == 8681 ~ "zone 2 to zone 4",
  cluster == 8684 ~ "zone 3 to zone 4",
  cluster == 9664 ~ "zone 3 to unemployment to zone 3",
  cluster == 9682 ~ "zone 2 to zone 3",
  cluster == 9698 ~ "zone 3",
  cluster == 10156 ~ "zone 2",
  cluster == 10161 ~ "zone 2 to unemployment to zone 2",
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))

seqdplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", axes = c(1,20), 
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))
seqrplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start", diss = seq.10cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

cluster_membership_visualization(veteran)
```

```{r creating-veteran-clusters, fig.height=10, fig.width=15}
# VETERANS -----------------------------------------------------------------------------
# Creating sequence objects for 10, 20, and 30 years after exiting the military for veterans 
seq.10 <- create_seq_vet_fixed("seq.10", 10, left_unemp = FALSE)
seq.20 <- create_seq_vet_fixed("seq.20", 20, left_unemp = FALSE)
seq.30 <- create_seq_vet_fixed("seq.30", 30, left_unemp = FALSE)

# Clustering sequnces
seq.10cluster_20 <- cluster("cluster_10", seq.10, sequence_option = "option 1", 20)
seq.20cluster_20 <- cluster("cluster_10", seq.20, sequence_option = "option 2", 20)
seq.30cluster_7 <- cluster("cluster_10", seq.30, sequence_option = "option 2", 7)
```

```{r veteran-clusters-ten-years, fig.height=10, fig.width=15}
# Visualizing 10 years 20 cluster solution ----------------------
seq.10cluster_20$cluster$stats

cluster_20 <- seq.10cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(781, 1360, 1435, 1511) ~ "education",
cluster %in% c(2607, 4345, 4416, 4690) ~ "promotion",
cluster %in% c(2769, 4409) ~ "demotion",
cluster %in% c(2727, 4303, 4390, 4684) ~ "unemployment",
cluster %in% c(2763, 2772, 4169, 4427, 4705, 4830) ~ "no change"
),
cluster_label = case_when(
  cluster == 781 ~ "zone 5 to education to zone 5",
  cluster == 1360 ~ "zone 4 to education to zone 4",
  cluster == 1435 ~ "education to zone 4",
  cluster == 1511 ~ "zone 4 to education",
  cluster == 2607 ~ "zone 4 to zone 5",
  cluster == 2727 ~ "zone 4 to unemployment to zone 5",
  cluster == 2763 ~ "zone 5",
  cluster == 2769 ~ "zone 5 to zone 4",
  cluster == 2772 ~ "zone 4 to zone 5 zone 4",
  cluster == 4169 ~ "zone 4 to zone 3 to zone 4",
  cluster == 4303 ~ "zone 4 to unemployment to zone 4",
  cluster == 4345 ~ "zone 3 to zone 4",
  cluster == 4390 ~ "zone 4 to unemployment",
  cluster == 4409 ~ "zone 4 to zone 3",
  cluster == 4416 ~ "zone 2 to zone 4",
  cluster == 4427 ~ "zone 4",
  cluster == 4684 ~ "zone 3 to unemployment",
  cluster == 4690 ~ "zone 2 to zone 3",
  cluster == 4705 ~ "zone 3",
  cluster == 4830 ~ "zone 2"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

# Plotting
seqdplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

seqrplot(seq.10, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, with.legend = F, sortv = "from.start", diss = seq.10cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

all_df <- all_df %>% mutate(end_onet55_label = case_when(
  end_onet55 == "55-3011.00" ~ "Air Crew Members",
  end_onet55 == "55-1011.00" ~ "Air Crew Officers",
  end_onet55 == "55-1012.00" ~ "Aircraft Launch and Recovery Officers",
  end_onet55 == "55-3012.00" ~ "Aircraft Launch and Recovery Specialists",
  end_onet55 == "55-3013.00" ~ "Armored Assault Vehicle Crew Members",
  end_onet55 == "55-1013.00" ~ "Armored Assault Vehicle Officers",
  end_onet55 == "55-3014.00" ~ "Artillery and Missile Crew Members",
  end_onet55 == "55-1014.00" ~ "Artillery and Missile Officers",
  end_onet55 == "55-1015.00" ~ "Command and Control Center Officers",
  end_onet55 == "55-3015.00" ~ "Command and Control Center Specialists",
  end_onet55 == "55-2011.00" ~ "First-Line Supervisors of Air Crew Members",
  end_onet55 == "55-2013.00" ~ "First-Line Supervisors of All Other Tactical Operations Specialists",
  end_onet55 == "55-2012.00" ~ "First-Line Supervisors of Weapons Specialists/Crew Members",
  end_onet55 == "55-3016.00" ~ "Infantry",
  end_onet55 == "55-1016.00" ~ "Infantry Officers",
  end_onet55 == "55-3019.00" ~ "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other",
  end_onet55 == "55-1019.00" ~ "Military Officer Special and Tactical Operations Leaders, All Other",
  end_onet55 == "55-3018.00" ~ "Special Forces",
  end_onet55 == "55-1017.00" ~ "Special Forces Officers",
), years_in_military_bin = factor(years_in_military_bin, levels = c("1 - 2", "3 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")), 
          year_military_enlist_bin = factor(year_military_enlist_bin, levels = c("Vietnam era (1964 to 1974)", "1975 to 1989", "1990 to 2000 (including Persian Gulf War)", "2001 or later")),
          career_before_military_bin = factor(career_before_military_bin, levels = c("0", "1 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")),
          year_entered_workforce_bin = factor(year_entered_workforce_bin, levels = c("Silent and Greatest", "Baby Boom", "Generation X", "Millennial")),
highest_degree = factor(highest_degree, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd")), 
highest_degree_from_forprofit = factor(highest_degree_from_forprofit, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd")),
highest_degree_from_hbcu = factor(highest_degree_from_hbcu, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd")))

cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)

cluster_membership_visualization(officer)
cluster_membership_visualization(end_onet55_label)
cluster_membership_visualization(years_in_military_bin)
cluster_membership_visualization(year_military_enlist_bin)
cluster_membership_visualization(career_before_military_bin)

cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)

dataset_all_skills$id <- as.character(dataset_all_skills$id)
all_df <- all_df %>% left_join(dataset_all_skills, by = "id")
dataset_all_majors$id <- as.character(dataset_all_majors$id)
all_df <- all_df %>% left_join(dataset_all_majors, by = "id")

  overall <- all_df %>% filter(!is.na(top_skill)) %>% mutate(total = n()) %>% group_by(cluster) %>% mutate(overall_cluster_count = n()) %>% group_by(top_skill) %>% mutate(overall_covariate_percent = round((n()/total * 100), 2)) %>% distinct(top_skill, overall_covariate_percent) %>% mutate(cluster_label = "overall", cluster_group = "overall", overall_cluster_percent = .1) %>% rename(cluster_covariate_percent = overall_covariate_percent)
nb.cols <- length(unique(all_df$top_skill))
mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(nb.cols)
all_df %>% filter(!is.na(top_skill)) %>% mutate(total = n()) %>% group_by(cluster) %>% mutate(overall_cluster_count = n(), overall_cluster_percent = n()/total) %>% group_by(top_skill) %>% mutate(overall_covariate_percent = round((n()/total * 100), 2)) %>% group_by(cluster, top_skill) %>% mutate(cluster_covariate_percent = round((n()/overall_cluster_count * 100), 2)) %>% distinct(cluster, cluster_label, cluster_group, top_skill, cluster_covariate_percent, overall_cluster_percent) %>% group_by(top_skill) %>% left_join(select(overall, overall = cluster_covariate_percent), by = "top_skill") %>% rbind(overall) %>% mutate(alpha = ifelse(!is.na(overall), abs((overall - cluster_covariate_percent)/overall), max(abs((overall - cluster_covariate_percent)/overall)))) %>%
  ggplot(aes(cluster_covariate_percent, cluster_label, fill = factor(top_skill), alpha = factor(alpha))) +
  geom_col(aes(width = overall_cluster_percent*10)) +
  facet_wrap(~ factor(cluster_group, levels = c("overall", "education", "promotion", "no change", "demotion", "unemployment")), ncol = 1, scales="free") + scale_fill_manual(values = mycolors) +
  scale_alpha_discrete(guide = "none")
test

cluster_membership_visualization(skill)
cluster_membership_visualization(major)

top_skill <- all_df %>%
  filter(!is.na(top_skill)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(top_skill) %>%
  mutate(total = n()) %>%
  group_by(cluster, top_skill) %>%
  mutate(percent = n()/total * 100, difference = (percent - cluster_percent)/percent) %>%
  distinct(top_skill, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(top_skill) %>% mutate(sum = sum(percent))

top_skill$cluster <- as.factor(top_skill$cluster)
top_skill <- top_skill %>% filter(!is.na(top_skill))
top_skill <- as.data.frame(top_skill)

ggplot(top_skill, aes(cluster_label, top_skill, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by top_skill") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~cluster_group, switch = "x", scales = "free_x", space = "free_x")

top_major <- all_df %>%
  filter(!is.na(top_major)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(top_major) %>%
  mutate(total = n()) %>%
  group_by(cluster, top_major) %>%
  mutate(percent = n()/total * 100, difference = (percent - cluster_percent)/percent) %>%
  distinct(top_major, cluster_long, cluster_group, cluster_label, percent, cluster_percent, difference) %>%
  group_by(top_major) %>% mutate(sum = sum(percent))

top_major$cluster <- as.factor(top_major$cluster)
top_major <- top_major %>% filter(!is.na(top_major))
top_major <- as.data.frame(top_major)

ggplot(top_major, aes(cluster_label, top_major, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, limits = c(-10, 10))+
  theme_classic()+
  labs(title = "Cluster membership by top_major") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~cluster_group, switch = "x", scales = "free_x", space = "free_x")

install.packages("ggpubr")
#ggballoonplot(aes(x = all_df$cluster, y = all_df%top_skill))

install.packages("FactoMineR")
install.packages("factoextra")
library(FactoMineR)

test <- all_df %>% select(cluster_label, cluster_group, top_skill) %>% mutate(value = 1)
table <- dcast(test, cluster_label ~ top_skill, fun.aggregate = sum)

res.ca <- CA(table, graph = FALSE)
fviz_ca_biplot(res.ca, repel = TRUE)

```

```{r veteran-clusters-twenty-years, fig.height=10, fig.width=15}
# Visualizing 20 years 20 cluster solution --------------------------------------------------
seq.20cluster_20$cluster$stats

cluster_20 <- seq.20cluster_20$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(91, 163, 343, 452) ~ "education",
cluster %in% c(628, 1020, 1071, 1348, 1643) ~ "promotion",
cluster %in% c(576, 1363, 1428, 1690, 1720) ~ "demotion",
cluster %in% c(668, 1078, 1566) ~ "unemployment",
cluster %in% c(1018, 1027, 1627) ~ "no change"
),
cluster_label = case_when(
  cluster == 91 ~ "education to unemployment",
  cluster == 163 ~ "zone 4 to education to zone 4",
  cluster == 343 ~ "education to zone 5",
  cluster == 452 ~ "education to zone 4",
  cluster == 576 ~ "zone 5 to zone 4",
  cluster == 628 ~ "zone 4 to zone 5 (early career)",
  cluster == 668 ~ "zone 4/5 to unemployment to zone 5",
  cluster == 1018 ~ "zone 4 to zone 5 to zone 4",
  cluster == 1020 ~ "zone 4 to zone 5 (late career)",
  cluster == 1027 ~ "zone 5",
  cluster == 1071 ~ "zone 3 to zone 4 (early career)",
  cluster == 1078 ~ "zone 4 to unemployment",
  cluster == 1348 ~ "zone 3 to zone 4 (mid career)",
  cluster == 1363 ~ "zone 4 to zone 3 (mid career)",
  cluster == 1428 ~ "zone 4 to zone 2 (mid career)",
  cluster == 1566 ~ "zone 4 to unemployment to zone 4",
  cluster == 1627 ~ "zone 4",
  cluster == 1643 ~ "zone 2 to zone 3",
  cluster == 1690 ~ "zone 4 to zone 3 (early career)",
  cluster == 1720 ~ "zone 4 to zone 2 (early career)"
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

# Plotting
seqdplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

seqrplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, with.legend = F, sortv = "from.start", diss = seq.20cluster_20$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

all_df <- all_df %>% mutate(end_onet55_label = case_when(
  end_onet55 == "55-3011.00" ~ "Air Crew Members",
  end_onet55 == "55-1011.00" ~ "Air Crew Officers",
  end_onet55 == "55-1012.00" ~ "Aircraft Launch and Recovery Officers",
  end_onet55 == "55-3012.00" ~ "Aircraft Launch and Recovery Specialists",
  end_onet55 == "55-3013.00" ~ "Armored Assault Vehicle Crew Members",
  end_onet55 == "55-1013.00" ~ "Armored Assault Vehicle Officers",
  end_onet55 == "55-3014.00" ~ "Artillery and Missile Crew Members",
  end_onet55 == "55-1014.00" ~ "Artillery and Missile Officers",
  end_onet55 == "55-1015.00" ~ "Command and Control Center Officers",
  end_onet55 == "55-3015.00" ~ "Command and Control Center Specialists",
  end_onet55 == "55-2011.00" ~ "First-Line Supervisors of Air Crew Members",
  end_onet55 == "55-2013.00" ~ "First-Line Supervisors of All Other Tactical Operations Specialists",
  end_onet55 == "55-2012.00" ~ "First-Line Supervisors of Weapons Specialists/Crew Members",
  end_onet55 == "55-3016.00" ~ "Infantry",
  end_onet55 == "55-1016.00" ~ "Infantry Officers",
  end_onet55 == "55-3019.00" ~ "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other",
  end_onet55 == "55-1019.00" ~ "Military Officer Special and Tactical Operations Leaders, All Other",
  end_onet55 == "55-3018.00" ~ "Special Forces",
  end_onet55 == "55-1017.00" ~ "Special Forces Officers",
), years_in_military_bin = factor(years_in_military_bin, levels = c("1 - 2", "3 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")), 
          year_military_enlist_bin = factor(year_military_enlist_bin, levels = c("Vietnam era (1964 to 1974)", "1975 to 1989", "1990 to 2000 (including Persian Gulf War)", "2001 or later")),
          career_before_military_bin = factor(career_before_military_bin, levels = c("0", "1 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")),
          year_entered_workforce_bin = factor(year_entered_workforce_bin, levels = c("Silent and Greatest", "Baby Boom", "Generation X", "Millennial")))

cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)

cluster_membership_visualization(officer)
cluster_membership_visualization(end_onet55_label)
cluster_membership_visualization(years_in_military_bin)
cluster_membership_visualization(year_military_enlist_bin)
cluster_membership_visualization(career_before_military_bin)

cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)

dataset_all_skills$id <- as.character(dataset_all_skills$id)
all_df <- all_df %>% left_join(dataset_all_skills, by = "id")
dataset_all_majors$id <- as.character(dataset_all_majors$id)
all_df <- all_df %>% left_join(dataset_all_majors, by = "id")

cluster_membership_visualization(skill)
cluster_membership_visualization(major)
```

```{r veteran-clusters-thirty-years, fig.height=10, fig.width=15}
# Visualizing 30 years 10 cluster solution -------------------------------------------------
seq.30cluster_7$cluster$stats

cluster_20 <- seq.30cluster_7$cluster$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id") %>% mutate(cluster_group = case_when(
  cluster %in% c(50, 122) ~ "education",
#cluster %in% c() ~ "promotion",
#cluster %in% c() ~ "demotion",
cluster %in% c(303) ~ "unemployment",
cluster %in% c(186, 229, 238, 314) ~ "no change",
),
cluster_label = case_when(
  cluster == 50 ~ "zone 4 to education to zone 4",
  cluster == 122 ~ "long unemployment spell to education",
  cluster == 186 ~ "zone 5",
  cluster == 229 ~ "zone 2",
  cluster == 238 ~ "zone 3",
  cluster == 303 ~ "zone 4 to short unemployment to zone 4",
  cluster == 314 ~ "zone 4",
), cluster_long = paste0(cluster_group, " - ", cluster_label))
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))
dataset_top_skills$id <- as.character(dataset_top_skills$id)
all_df <- all_df %>% left_join(dataset_top_skills, by = "id")
dataset_top_majors$id <- as.character(dataset_top_majors$id)
all_df <- all_df %>% left_join(dataset_top_majors, by = "id")

# Plotting
seqdplot(seq.30, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))

seqrplot(seq.30, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, with.legend = F, sortv = "from.start", diss = seq.30cluster_7$diss,
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5"))

all_df <- all_df %>% mutate(end_onet55_label = case_when(
  end_onet55 == "55-3011.00" ~ "Air Crew Members",
  end_onet55 == "55-1011.00" ~ "Air Crew Officers",
  end_onet55 == "55-1012.00" ~ "Aircraft Launch and Recovery Officers",
  end_onet55 == "55-3012.00" ~ "Aircraft Launch and Recovery Specialists",
  end_onet55 == "55-3013.00" ~ "Armored Assault Vehicle Crew Members",
  end_onet55 == "55-1013.00" ~ "Armored Assault Vehicle Officers",
  end_onet55 == "55-3014.00" ~ "Artillery and Missile Crew Members",
  end_onet55 == "55-1014.00" ~ "Artillery and Missile Officers",
  end_onet55 == "55-1015.00" ~ "Command and Control Center Officers",
  end_onet55 == "55-3015.00" ~ "Command and Control Center Specialists",
  end_onet55 == "55-2011.00" ~ "First-Line Supervisors of Air Crew Members",
  end_onet55 == "55-2013.00" ~ "First-Line Supervisors of All Other Tactical Operations Specialists",
  end_onet55 == "55-2012.00" ~ "First-Line Supervisors of Weapons Specialists/Crew Members",
  end_onet55 == "55-3016.00" ~ "Infantry",
  end_onet55 == "55-1016.00" ~ "Infantry Officers",
  end_onet55 == "55-3019.00" ~ "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other",
  end_onet55 == "55-1019.00" ~ "Military Officer Special and Tactical Operations Leaders, All Other",
  end_onet55 == "55-3018.00" ~ "Special Forces",
  end_onet55 == "55-1017.00" ~ "Special Forces Officers",
), years_in_military_bin = factor(years_in_military_bin, levels = c("1 - 2", "3 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")), 
          year_military_enlist_bin = factor(year_military_enlist_bin, levels = c("Vietnam era (1964 to 1974)", "1975 to 1989", "1990 to 2000 (including Persian Gulf War)", "2001 or later")),
          career_before_military_bin = factor(career_before_military_bin, levels = c("0", "1 - 4", "5 - 10", "11 - 20", "21 - 30", "31+")),
          year_entered_workforce_bin = factor(year_entered_workforce_bin, levels = c("Silent and Greatest", "Baby Boom", "Generation X", "Millennial")))

cluster_membership_visualization(highest_degree)
cluster_membership_visualization(gender)
cluster_membership_visualization(irr_bin)
cluster_membership_visualization(highest_degree_from_forprofit)
cluster_membership_visualization(highest_degree_from_hbcu)
cluster_membership_visualization(year_entered_workforce_bin)

cluster_membership_visualization(officer)
cluster_membership_visualization(end_onet55_label)
cluster_membership_visualization(years_in_military_bin)
cluster_membership_visualization(year_military_enlist_bin)
cluster_membership_visualization(career_before_military_bin)

cluster_membership_visualization(top_skill)
cluster_membership_visualization(top_major)

dataset_all_skills$id <- as.character(dataset_all_skills$id)
all_df <- all_df %>% left_join(dataset_all_skills, by = "id")
dataset_all_majors$id <- as.character(dataset_all_majors$id)
all_df <- all_df %>% left_join(dataset_all_majors, by = "id")

cluster_membership_visualization(skill)
cluster_membership_visualization(major)
```








```{r}
all_df %>% filter(!is.na(highest_degree), highest_degree != "post-bacc") %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree")
all_df %>% group_by(cluster) %>% filter(!is.na(gender)) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(gender) %>%
  mutate(total = n()) %>%
  group_by(cluster, gender) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(gender, cluster, percent, cluster_percent, difference) %>%
  group_by(gender) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, gender, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by gender")
all_df %>% group_by(cluster) %>% filter(highest_degree_from_forprofit != "highschool") %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_forprofit) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_forprofit) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_forprofit, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_forprofit) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_forprofit, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from forprofit")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_hbcu) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_hbcu) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_hbcu, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_hbcu) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_hbcu, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from hbcu")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(irr_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, irr_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(irr_bin, cluster, percent, cluster_percent, difference) %>%
  group_by(irr_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, irr_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by IRR")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(officer) %>%
  mutate(total = n()) %>%
  group_by(cluster, officer) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(officer, cluster, percent, cluster_percent, difference) %>%
  group_by(officer) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, officer, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by officer")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(end_onet55) %>%
  mutate(total = n()) %>% filter(total > 10) %>%
  group_by(cluster, end_onet55) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(end_onet55, cluster, percent, cluster_percent, difference) %>%
  group_by(end_onet55) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, end_onet55, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by ending onet 55")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_military_enlist_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_military_enlist_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_military_enlist_bin, percent, cluster_percent, difference) %>%
  group_by(year_military_enlist_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_military_enlist_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year military enlist")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_entered_workforce_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_entered_workforce_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_entered_workforce_bin, percent, cluster_percent, difference) %>%
  group_by(year_entered_workforce_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_entered_workforce_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year entered the workforce")

# Visualizing 10 years 20 cluster solution
seq.20cluster_20$stats

cluster_20 <- seq.20cluster_20$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.10)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
ggplot(veteran, aes(cluster, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Clustering membership by veteran")

# Visualizing 30 years 20 cluster solution
seq.30cluster_5$stats

cluster_5 <- seq.30cluster_5$clustering
cluster_5_fac <- factor(cluster_5)
all <- rownames(seq.30)
all_df <- as.data.frame(cbind(all, cluster_5))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(veteran, cluster, percent, cluster_percent, difference) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
veteran <- veteran %>% filter(!is.na(veteran))
veteran <- as.data.frame(veteran)

seqdplot(seq.30, group = cluster_5_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
ggplot(veteran, aes(cluster, veteran, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Clustering membership by veteran")

```
```{r}

all_df %>% filter(!is.na(highest_degree), highest_degree != "post-bacc") %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree")
all_df %>% group_by(cluster) %>% filter(!is.na(gender)) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(gender) %>%
  mutate(total = n()) %>%
  group_by(cluster, gender) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(gender, cluster, percent, cluster_percent, difference) %>%
  group_by(gender) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, gender, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by gender")
all_df %>% group_by(cluster) %>% filter(highest_degree_from_forprofit != "highschool") %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_forprofit) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_forprofit) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_forprofit, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_forprofit) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_forprofit, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from forprofit")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_hbcu) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_hbcu) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_hbcu, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_hbcu) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_hbcu, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from hbcu")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(irr_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, irr_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(irr_bin, cluster, percent, cluster_percent, difference) %>%
  group_by(irr_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, irr_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by IRR")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(officer) %>%
  mutate(total = n()) %>%
  group_by(cluster, officer) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(officer, cluster, percent, cluster_percent, difference) %>%
  group_by(officer) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, officer, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by officer")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(end_onet55) %>%
  mutate(total = n()) %>% filter(total > 10) %>%
  group_by(cluster, end_onet55) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(end_onet55, cluster, percent, cluster_percent, difference) %>%
  group_by(end_onet55) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, end_onet55, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by ending onet 55")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_military_enlist_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_military_enlist_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_military_enlist_bin, percent, cluster_percent, difference) %>%
  group_by(year_military_enlist_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_military_enlist_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year military enlist")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_entered_workforce_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_entered_workforce_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_entered_workforce_bin, percent, cluster_percent, difference) %>%
  group_by(year_entered_workforce_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_entered_workforce_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year entered the workforce")

# Visualizing 20 years 20 cluster solution
seq.20cluster_20$stats

cluster_20 <- seq.20cluster_20$clustering
cluster_20_fac <- factor(cluster_20)
all <- rownames(seq.20)
all_df <- as.data.frame(cbind(all, cluster_20))
colnames(all_df) <- c("id", "cluster")
covariates <- bg_covariates
covariates$id <- as.character(covariates$id)

all_df <- left_join(all_df, covariates, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_forprofit, by = "id")
all_df <- all_df %>% left_join(highest_degree_from_hbcu, by = "id")
all_df <- all_df %>% mutate(irr_bin = ntile(irr, 5))

# Plotting
seqdplot(seq.20, group = cluster_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))

all_df %>% filter(!is.na(highest_degree), highest_degree != "post-bacc") %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree")
all_df %>% group_by(cluster) %>% filter(!is.na(gender)) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(gender) %>%
  mutate(total = n()) %>%
  group_by(cluster, gender) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(gender, cluster, percent, cluster_percent, difference) %>%
  group_by(gender) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, gender, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by gender")
all_df %>% group_by(cluster) %>% filter(highest_degree_from_forprofit != "highschool") %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_forprofit) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_forprofit) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_forprofit, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_forprofit) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_forprofit, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from forprofit")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(highest_degree_from_hbcu) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree_from_hbcu) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(highest_degree_from_hbcu, cluster, percent, cluster_percent, difference) %>%
  group_by(highest_degree_from_hbcu) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, highest_degree_from_hbcu, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by highest degree from hbcu")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(irr_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, irr_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(irr_bin, cluster, percent, cluster_percent, difference) %>%
  group_by(irr_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, irr_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by IRR")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(officer) %>%
  mutate(total = n()) %>%
  group_by(cluster, officer) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(officer, cluster, percent, cluster_percent, difference) %>%
  group_by(officer) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, officer, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by officer")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(end_onet55) %>%
  mutate(total = n()) %>% filter(total > 10) %>%
  group_by(cluster, end_onet55) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(end_onet55, cluster, percent, cluster_percent, difference) %>%
  group_by(end_onet55) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, end_onet55, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by ending onet 55")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_military_enlist_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_military_enlist_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_military_enlist_bin, percent, cluster_percent, difference) %>%
  group_by(year_military_enlist_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_military_enlist_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year military enlist")
all_df %>% group_by(cluster) %>% mutate(cluster_total = n()) %>% ungroup() %>% mutate(cluster_percent = cluster_total/n() * 100) %>%
  group_by(year_entered_workforce_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_entered_workforce_bin) %>%
  mutate(percent = n()/total * 100, difference = percent - cluster_percent) %>%
  distinct(cluster, year_entered_workforce_bin, percent, cluster_percent, difference) %>%
  group_by(year_entered_workforce_bin) %>% mutate(sum = sum(percent)) %>%
ggplot(aes(cluster, year_entered_workforce_bin, fill= difference)) + 
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0)+
  theme_classic()+
  labs(title = "Cluster membership by year entered the workforce")
```



```{r clustering, fig.height=10, fig.width=15}
vet.seq <- create_seq_vet_fixed("vet.seq", 10, left_unemp = TRUE)

transition_matrix <- seqtrate(vet.seq, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

# OPTION 1 : OUR OM SPELL, LOW EXPANSION COST AND LOW WEIGHT
sequencing.opt1 <- seqdist(vet.seq, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)

# OPTION 2 : OUR OM
sequencing.opt2 <- seqdist(vet.seq, method = "OMstran", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0.5)

# OPTION 3 : OUR OM, LOW WEIGHT ON ORIGIN
sequencing.opt3 <- seqdist(vet.seq, method = "OMstran", indel = 1, sm = cost_matrix, with.missing = TRUE, otto = 0.01)

# CLUSTERING
numbers <- (2:20)
pamstats <- NULL
#rownames(pamstats) <- numbers
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt1, k = number)
  assign(paste0("sequencing.pam.opt1.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt1 <- dplyr::bind_rows(pamstats)
pamstats <- NULL
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt2, k = number)
  assign(paste0("sequencing.pam.opt2.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt2 <- dplyr::bind_rows(pamstats)
for (number in numbers) {
  clusterpam <- wcKMedoids(sequencing.opt3, k = number)
  assign(paste0("sequencing.pam.opt3.", number), clusterpam, envir = .GlobalEnv)
  pamstats[[number]] <- clusterpam$stats
}
pamstats.opt3 <- dplyr::bind_rows(pamstats)

# QUALITY METRICS
rownames(pamstats.opt1) <- numbers
PAM.ASW.Opt1 <- as.matrix(pamstats.opt1$ASW)
colnames(PAM.ASW.Opt1) <- c("ASW opt1")
PAM.ASW.Opt2 <- as.matrix(pamstats.opt2$ASW)
colnames(PAM.ASW.Opt2) <- c("ASW opt2")
PAM.ASW.Opt3 <- as.matrix(pamstats.opt3$ASW)
colnames(PAM.ASW.Opt3) <- c("ASW opt3")
PAM.ASW <- bind_cols(PAM.ASW.Opt1, PAM.ASW.Opt2, PAM.ASW.Opt3)
PAM.ASW <- PAM.ASW %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.ASW$rowname <- as.numeric(PAM.ASW$rowname)

rownames(pamstats.opt1) <- numbers
PAM.HC.Opt1 <- as.matrix(pamstats.opt1$HC)
colnames(PAM.HC.Opt1) <- c("HC opt1")
PAM.HC.Opt2 <- as.matrix(pamstats.opt2$HC)
colnames(PAM.HC.Opt2) <- c("HC opt2")
PAM.HC.Opt3 <- as.matrix(pamstats.opt3$HC)
colnames(PAM.HC.Opt3) <- c("HC opt3")
PAM.HC <- bind_cols(PAM.HC.Opt1, PAM.HC.Opt2, PAM.HC.Opt3)
PAM.HC <- PAM.HC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.HC$rowname <- as.numeric(PAM.HC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.PBC.Opt1 <- as.matrix(pamstats.opt1$PBC)
colnames(PAM.PBC.Opt1) <- c("PBC opt1")
PAM.PBC.Opt2 <- as.matrix(pamstats.opt2$PBC)
colnames(PAM.PBC.Opt2) <- c("PBC opt2")
PAM.PBC.Opt3 <- as.matrix(pamstats.opt3$PBC)
colnames(PAM.PBC.Opt3) <- c("PBC opt3")
PAM.PBC <- bind_cols(PAM.PBC.Opt1, PAM.PBC.Opt2, PAM.PBC.Opt3)
PAM.PBC <- PAM.PBC %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.PBC$rowname <- as.numeric(PAM.PBC$rowname)

rownames(pamstats.opt1) <- numbers
PAM.R2.Opt1 <- as.matrix(pamstats.opt1$R2)
colnames(PAM.R2.Opt1) <- c("R2 opt1")
PAM.R2.Opt2 <- as.matrix(pamstats.opt2$R2)
colnames(PAM.R2.Opt2) <- c("R2 opt2")
PAM.R2.Opt3 <- as.matrix(pamstats.opt3$R2)
colnames(PAM.R2.Opt3) <- c("R2 opt3")
PAM.R2 <- bind_cols(PAM.R2.Opt1, PAM.R2.Opt2, PAM.R2.Opt3)
PAM.R2 <- PAM.R2 %>% rownames_to_column() %>% melt() %>% mutate(group = "pam")
PAM.R2$rowname <- as.numeric(PAM.R2$rowname)

PAM.ASW %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.HC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.PBC %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

PAM.R2 %>% mutate(clusters = rowname + 1) %>%
ggplot(aes(x = variable, y = clusters, fill = value)) +
  #facet_grid(. ~ group, scales = "free") +
  geom_tile() +
  scale_fill_continuous(name = "ASW value", type = "viridis") +
  labs(title = "Sequencing - ASW (optimal 1)", caption = "Average silhouette width (ASW) is the coherence of assignments, high coherence indicates high between-group distances and strong
within-group homogeneity \n Dissimiarlity options:\n Option 1: Optimal matching of spell sequences, low expansion cost, low weight, using our custom cost matrix \n Option 2: Optimal matching of transition sequences using our custom cost matrix \n Option 3: Optimal matching of transition sequences, low weight, using our custom cost matrix") +
  scale_x_discrete(name = "dissimilarity option", labels = c("1", "2", "3")) +
  ylab("number of clusters") +
  ylim(1,21) +
  theme_bw()

clusterpam <- wcKMedoids(sequencing.opt2, k = 20)
clusterpam$stats

clusterpam_20 <- clusterpam$clustering
clusterpam_20_fac <- factor(clusterpam_20)#, #labels = paste("Type", 1:20))

seqdplot(vet.seq, group = clusterpam_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
seqlegend(vet.seq, cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))

vet <- rownames(vet.seq)

vet_df <- as.data.frame(cbind(vet, clusterpam_20))
colnames(vet_df) <- c("id", "cluster")
bg_covariates$id <- as.character(bg_covariates$id)

vet_df <- left_join(vet_df, bg_covariates, by = "id")

degree <- vet_df %>%
  filter(!is.na(highest_degree)) %>%
  group_by(highest_degree) %>%
  mutate(total = n()) %>%
  group_by(cluster, highest_degree) %>%
  mutate(percent = n()/total) %>% distinct(highest_degree, cluster, percent) %>%
  group_by(highest_degree) %>% mutate(sum = sum(percent))

degree$cluster <- as.factor(degree$cluster)
degree$highest_degree <- factor(degree$highest_degree, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd"))
degree <- degree %>% filter(!is.na(highest_degree))

degree <- as.data.frame(degree)

ggplot(degree, aes(cluster, highest_degree, fill= percent)) + 
  geom_tile()+
  scale_fill_gradient(low="white", high="blue")+
  theme_classic()+
  labs(title = "Clustering X Degree --before normalization")

year_entered_workforce_bin <- vet_df %>%
  filter(!is.na(year_entered_workforce_bin)) %>%
  group_by(year_entered_workforce_bin) %>%
  mutate(total = n()) %>%
  group_by(cluster, year_entered_workforce_bin) %>%
  mutate(percent = n()/total) %>% distinct(cluster, year_entered_workforce_bin, percent) %>%
  group_by(year_entered_workforce_bin) %>% mutate(sum = sum(percent))

year_entered_workforce_bin$cluster <- as.factor(year_entered_workforce_bin$cluster)
#irr_bin$highest_degree <- factor(irr_bin$highest_degree, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd"))
#degree <- degree %>% filter(!is.na(highest_degree))

year_entered_workforce_bin <- as.data.frame(year_entered_workforce_bin)

seqdplot(vet.seq, group = clusterpam_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))

ggplot(year_entered_workforce_bin, aes(cluster, year_entered_workforce_bin, fill= percent)) + 
  geom_tile()+
  scale_fill_gradient(low="white", high="blue")+
  theme_classic()+
  labs(title = "Clustering X Degree --before normalization")


transition_matrix <- seqtrate(seq.20, weighted=FALSE, count=TRUE)
round(transition_matrix,2)
diag(transition_matrix) = 0
round(transition_matrix,2)
rowsum <- apply(transition_matrix, 1, sum)
for(i in 1:nrow(transition_matrix)) {
  for (j in 1:ncol(transition_matrix)){
    transition_matrix[i,j] = transition_matrix[i,j]/rowsum[i]
  }
}
for(j in 1:ncol(transition_matrix)){
      transition_matrix[7,j] = transition_matrix[7,j] = 0
}
transition_matrix <- round(transition_matrix,2)
cost_matrix <- 2-transition_matrix
round(cost_matrix,2)
diag(cost_matrix) = 0
cost_matrix <- round(cost_matrix,2)

sequencing.opt1 <- seqdist(seq.10, method = "OMspell", indel = "auto", sm = cost_matrix, with.missing = TRUE, otto = 0, expcost = 0)

clusterpam <- wcKMedoids(sequencing.opt1, k = 20)
clusterpam$stats

clusterpam_20 <- clusterpam$clustering
clusterpam_20_fac <- factor(clusterpam_20)#, #labels = paste("Type", 1:20))

#seqdplot(seq.20, group = clusterpam_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
#         cpal = c(uva_color_palette[1], uva_color_palette[2],
#                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
#                  uva_color_palette[5], "#CBBEB5", "dark gray"))
#seqlegend(seq.10, cpal = c(uva_color_palette[1], uva_color_palette[2],
#                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
#                  uva_color_palette[5], "#CBBEB5", "dark gray"))

all <- rownames(seq.20)

all_df <- as.data.frame(cbind(all, clusterpam_20))
colnames(all_df) <- c("id", "cluster")
bg_covariates$id <- as.character(bg_covariates$id)

all_df <- left_join(all_df, bg_covariates, by = "id")

veteran <- all_df %>%
  filter(!is.na(veteran)) %>%
  group_by(veteran) %>%
  mutate(total = n()) %>%
  group_by(cluster, veteran) %>%
  mutate(percent = n()/total) %>% distinct(veteran, cluster, percent) %>%
  group_by(veteran) %>% mutate(sum = sum(percent))

veteran$cluster <- as.factor(veteran$cluster)
#degree$veteran <- factor(degree$highest_degree, levels = c("highschool", "GED/diploma", "associates", "bachelors", "masters", "phd"))
veteran <- veteran %>% filter(!is.na(veteran))

veteran <- as.data.frame(veteran)

seqdplot(seq.20, group = clusterpam_20_fac, border = NA, use.layout = TRUE, cols = 5, withlegend = F, sortv = "from.start",
         cpal = c(uva_color_palette[1], uva_color_palette[2],
                  uva_color_palette[4], uva_color_palette[6], uva_color_palette[9],
                  uva_color_palette[5], "#CBBEB5", "dark gray"))
ggplot(veteran, aes(cluster, veteran, fill= percent)) + 
  geom_tile()+
  scale_fill_gradient(low="white", high="blue")+
  theme_classic()+
  labs(title = "Clustering X Degree --before normalization")

```
