---
title: "General Project Overview"
description: "Main findings and outline"
weight: 1
draft: false
output: html_document
---

### Main Findings 

From our research, we have come to several major findings.

#### Data profiling, benchmarking, and exploration.
##### 1. BGT resume data overrepresents young and white collar veterans.

<br/>

#### Sequence analysis
##### 2. While there is some evidence to support career mobility for veterans over the entire career, there is little evidence to support career mobility for veterans as a group in the first ten years after they exit the military.
##### 3. Almost half of veterans are in a state of unemployment in the first and tenth years after they exit the military.

<br>

#### Clustering of sequences
##### 4. Sequence clusters characterized by a higher average job zone also contain more advanced degree earners.
##### 5. Sequence clusters characterized by retirement in the first ten years after exiting the military also contain more female veterans.

<br>

#### Tournament theory hypothesis
##### 6. Promotion in the first two years after military exit affects later employment outcomes, being associated with future employment.
##### 7. Military transitional unemployment in the first two years after military exit affects later employment outcomes, being associated with future unemployment and finishing in a lower job zone.

#### Future work

[Here you will describe the results and include important visualizations from your project.] 

### Conclusion and Policy Implications 

[Here you could highlight the main takeaways and the potential policy implications of your findings.] 

### References 

[List your references here using APA format (or at least standardize all of the references using the same format).]

